// Shared location picker. Wires the header geo button on every page to open
// a modal with a Country <select> and a City <select>. The city dropdown is
// enabled only after a country is chosen and is populated with that country's
// cities. On confirm it resolves the chosen city to lat/lon, overwrites the
// saved location, and dispatches a `location:changed` event so pages reload.
(function () {
          const COUNTRIES = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bonaire",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Cook Islands",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czechia",
    "Côte d'Ivoire",
    "Denmark",
    "Deyang",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See (Vatican City State)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "North Korea",
    "North Macedonia",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Romania",
    "Russia",
    "Russian Federation",
    "Rwanda",
    "Réunion",
    "Saint Barthélemy",
    "Saint Helena",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin (French part)",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Saitama",
    "Samoa",
    "San Marino",
    "Santa Caterina i La Ribera",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten (Dutch part)",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Sweden",
    "Switzerland",
    "Syria",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands",
    "Tuvalu",
    "Türkiye",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Viet Nam",
    "Vietnam",
    "Virgin Islands",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    "Åland Islands"
  ];

  // Major cities per country (capital + a few extras). Only names are stored;
  // coordinates are resolved on confirm via the geocoding API.
    const CITIES_BY_COUNTRY = {
  "Afghanistan": [
    "Kabul",
    "Kandahar",
    "Herat",
    "Mazar-i-Sharif",
    "Kunduz",
    "Jalalabad",
    "Ghazni",
    "Bamyan",
    "Nīlī",
    "Jurm",
    "Aībak",
    "Kushk",
    "Khōst",
    "Khulm",
    "Khāsh",
    "Herāt",
    "Farah",
    "Balkh",
    "Āsmār",
    "Zaranj",
    "Rustāq",
    "Qarqīn",
    "Nahrīn",
    "Karukh",
    "Gardez",
    "Bāmyān",
    "Taloqan",
    "Shahrak",
    "Qarāwul",
    "Paghmān",
  ],
  "Albania": [
    "Tirana",
    "Durrës",
    "Vlorë",
    "Elbasan",
    "Shkodër",
    "Fier",
    "Korçë",
    "Berat",
    "Kukës",
    "Peqin",
    "Patos",
    "Lezhë",
    "Krujë",
    "Kuçovë",
    "Kavajë",
    "Sarandë",
    "Bulqizë",
    "Lushnjë",
    "Pogradec",
    "Librazhd",
    "Rrashbull",
    "Fier-Çifçi",
    "Gjirokastër",
    "Patos Fshat",
    "Fushë-Krujë",
  ],
  "Algeria": [
    "Algiers",
    "Oran",
    "Constantine",
    "Annaba",
    "Blida",
    "Batna",
    "Sétif",
    "Tlemcen",
    "Béjaïa",
    "Skikda",
    "Sig",
    "Mila",
    "Kaïs",
    "Tolga",
    "Ténès",
    "Souma",
    "Saïda",
    "Mekla",
    "Médéa",
    "Kolea",
    "Jijel",
    "Gdyel",
    "Freha",
    "Chlef",
    "Drean",
    "Arzew",
    "Arris",
    "Akbou",
    "Aflou",
    "Adrar",
  ],
  "Andorra": [
    "Andorra la Vella",
    "Escaldes-Engordany",
    "Sant Julià de Lòria",
    "Encamp",
    "La Massana",
    "les Escaldes",
  ],
  "Angola": [
    "Luanda",
    "Huambo",
    "Lobito",
    "Benguela",
    "Namibe",
    "Cabinda",
    "Malanje",
    "Saurimo",
    "Luau",
    "Uíge",
    "Úcua",
    "Soyo",
    "Piri",
    "Gama",
    "Cela",
    "Dundo",
    "Nzagi",
    "Viana",
    "Songo",
    "Gombe",
    "Dondo",
    "Dondo",
    "Cuilo",
    "Golfe",
    "Virei",
    "Ucuma",
    "Sumbe",
    "Mungo",
    "Luena",
    "Cuíto",
  ],
  "Antigua and Barbuda": [
    "Saint John's",
    "All Saints",
    "Liberta",
    "Bolans",
    "Potter's Village",
    "Saint John’s",
  ],
  "Argentina": [
    "Buenos Aires",
    "Cordoba",
    "Rosario",
    "Mendoza",
    "Tucuman",
    "La Plata",
    "Mar del Plata",
    "Salta",
    "Santa Fe",
    "San Juan",
    "Bahia Blanca",
    "San Miguel de Tucuman",
    "Goya",
    "Azul",
    "Vera",
    "Tigre",
    "Pilar",
    "Oberá",
    "Muñiz",
    "Morón",
    "Merlo",
    "Haedo",
    "Luján",
    "Colón",
    "Boedo",
    "Salto",
    "Pérez",
    "Junín",
    "Allen",
    "Zárate",
  ],
  "Armenia": [
    "Yerevan",
    "Gyumri",
    "Vanadzor",
    "Vagharshapat",
    "Abovyan",
    "Kapan",
    "Avan",
    "Goris",
    "Sevan",
    "Masis",
    "Gavar",
    "Artik",
    "Ararat",
    "Ijevan",
    "Hrazdan",
    "Armavir",
    "Dilijan",
    "Erebuni",
    "Kentron",
    "Arabkir",
    "Artashat",
    "Ashtarak",
    "Nor Nork",
    "Ajapnyak",
    "Davtashen",
    "Shengavit",
    "Charentsavan",
    "Kanaker-Zeytun",
    "Malatia-Sebastia",
  ],
  "Australia": [
    "Canberra",
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Newcastle",
    "Hobart",
    "Darwin",
    "Wollongong",
    "Geelong",
    "Townsville",
    "Kew",
    "Ryde",
    "Lara",
    "Taree",
    "Manly",
    "Lalor",
    "Dubbo",
    "Corio",
    "Gawler",
    "Byford",
    "Albany",
    "Wallan",
    "Orange",
    "Nerang",
    "Mosman",
    "Mernda",
    "Mascot",
  ],
  "Austria": [
    "Vienna",
    "Graz",
    "Linz",
    "Salzburg",
    "Innsbruck",
    "Klagenfurt",
    "Villach",
    "Wels",
    "Sankt Pölten",
    "Dornbirn",
    "Lend",
    "Traun",
    "Telfs",
    "Steyr",
    "Pradl",
    "Baden",
    "Gries",
    "Wilten",
    "Aspern",
    "Neubau",
    "Döbling",
    "Mödling",
    "Penzing",
    "Hötting",
    "Hernals",
    "Essling",
    "Bregenz",
    "Bludenz",
    "Geidorf",
    "Andritz",
  ],
  "Azerbaijan": [
    "Baku",
    "Ganja",
    "Sumqayit",
    "Mingachevir",
    "Shirvan",
    "Nakhchivan",
    "Ujar",
    "Quba",
    "Gobu",
    "Lerik",
    "Saray",
    "Sheki",
    "Qusar",
    "Jorat",
    "Barda",
    "Aghsu",
    "Ağdaş",
    "Shusha",
    "Salyan",
    "Saatlı",
    "Nehram",
    "Fuzuli",
    "Astara",
    "Şirvan",
    "Aghdam",
    "Zabrat",
    "Goygol",
    "Xaçmaz",
    "Tartar",
    "Gazakh",
  ],
  "Bahamas": [
    "Nassau",
    "Freeport",
    "West End",
    "Cooper's Town",
    "Marsh Harbour",
    "Lucaya",
    "Killarney",
  ],
  "Bahrain": [
    "Manama",
    "Riffa",
    "Muharraq",
    "Isa Town",
    "Sitrah",
    "Ar Rifā‘",
    "Jidd Ḩafş",
    "Dār Kulayb",
    "Al Muharraq",
    "Madīnat ‘Īsá",
    "Madīnat Ḩamad",
  ],
  "Bangladesh": [
    "Dhaka",
    "Chittagong",
    "Khulna",
    "Rajshahi",
    "Sylhet",
    "Barisal",
    "Rangpur",
    "Comilla",
    "Feni",
    "Bera",
    "Tungi",
    "Dohār",
    "Kālia",
    "Bhola",
    "Pābna",
    "Bogra",
    "Savar",
    "Teknāf",
    "Patiya",
    "Mathba",
    "Rāipur",
    "Narail",
    "Raojān",
    "Pālang",
    "Maijdi",
    "Kafrul",
    "Natona",
    "Puthia",
    "Natore",
    "Bhanga",
  ],
  "Barbados": [
    "Bridgetown",
    "Speightstown",
    "Oistins",
    "Bathsheba",
    "Holetown",
  ],
  "Belarus": [
    "Minsk",
    "Gomel",
    "Mogilev",
    "Vitebsk",
    "Grodno",
    "Brest",
    "Bobruisk",
    "Lida",
    "Pinsk",
    "Orsha",
    "Mazyr",
    "Horki",
    "Slutsk",
    "Slonim",
    "Kobryn",
    "Hrodna",
    "Bykhov",
    "Zhlobin",
    "Vileyka",
    "Smarhoń",
    "Polotsk",
    "Pastavy",
    "Nesvizh",
    "Logoysk",
    "Krychaw",
    "Ivanovo",
    "Homyel",
    "Dobrush",
    "Byaroza",
    "Barysaw",
  ],
  "Belgium": [
    "Brussels",
    "Antwerp",
    "Ghent",
    "Charleroi",
    "Liège",
    "Bruges",
    "Namur",
    "Leuven",
    "Mons",
    "Aalst",
    "Mol",
    "Huy",
    "Ath",
    "Ans",
    "Zele",
    "Visé",
    "Peer",
    "Lier",
    "Lede",
    "Gent",
    "Genk",
    "Geel",
    "Dour",
    "Boom",
    "Asse",
    "Zemst",
    "Wavre",
    "Uccle",
    "Tielt",
    "Temse",
  ],
  "Belize": [
    "Belize City",
    "San Ignacio",
    "Orange Walk",
    "Belmopan",
    "Dangriga",
    "San Pedro",
  ],
  "Benin": [
    "Porto-Novo",
    "Cotonou",
    "Djougou",
    "Bohicon",
    "Parakou",
    "Abomey-Calavi",
    "Zé",
    "Sé",
    "Semi",
    "Savé",
    "Pobé",
    "Ekpé",
    "Cové",
    "Comé",
    "Tobré",
    "Nikki",
    "Ndali",
    "Kétou",
    "Kérou",
    "Kandi",
    "Dogbo",
    "Banté",
    "Ouaké",
    "Cobly",
    "Zinvié",
    "Sakété",
    "Pèrèrè",
    "Ouinhi",
    "Ouidah",
    "Ouessé",
  ],
  "Bhutan": [
    "Thimphu",
    "Phuntsholing",
    "Punakha",
    "Paro",
    "Gelephu",
    "Punākha",
    "Tsirang",
  ],
  "Bolivia": [
    "Laja",
    "Vinto",
    "Sucre",
    "Oruro",
    "Warnes",
    "Viacha",
    "Tupiza",
    "Tarija",
    "Sacaba",
    "Punata",
    "Potosí",
    "Mizque",
    "La Paz",
    "Cotoca",
    "Cobija",
    "Camiri",
    "Yacuiba",
    "Montero",
    "Huanuni",
    "Bermejo",
    "Villazón",
    "Trinidad",
    "El Torno",
    "Caranavi",
    "Tiquipaya",
    "Sipe Sipe",
    "Riberalta",
    "Llallagua",
    "Achocalla",
    "San Borja",
  ],
  "Bosnia and Herzegovina": [
    "Sarajevo",
    "Banja Luka",
    "Tuzla",
    "Zenica",
    "Mostar",
    "Bijeljina",
    "Doboj",
    "Cazin",
    "Brčko",
    "Bihać",
    "Visoko",
    "Ilidža",
    "Konjic",
    "Travnik",
    "Lukavac",
    "Goražde",
    "Bugojno",
    "Trebinje",
    "Prijedor",
    "Gradačac",
    "Gračanica",
    "Velika Kladuša",
    "Bosanska Krupa",
  ],
  "Botswana": [
    "Gaborone",
    "Francistown",
    "Molepolole",
    "Maun",
    "Serowe",
    "Selibe Phikwe",
    "Kanye",
    "Tonota",
    "Mosopa",
    "Janeng",
    "Ghanzi",
    "Gabane",
    "Tutume",
    "Thamaga",
    "Palapye",
    "Mochudi",
    "Lobatse",
    "Mmopone",
    "Jwaneng",
    "Tlokweng",
    "Ramotswa",
    "Bobonong",
    "Mahalapye",
    "Letlhakane",
    "Mogoditshane",
    "Selebi-Phikwe",
  ],
  "Brazil": [
    "Brasília",
    "Sao Paulo",
    "Rio de Janeiro",
    "Salvador",
    "Fortaleza",
    "Belo Horizonte",
    "Manaus",
    "Curitiba",
    "Recife",
    "Porto Alegre",
    "Goiânia",
    "Belém",
    "Natal",
    "Maceió",
    "Se",
    "Ipu",
    "Icó",
    "Exu",
    "Açu",
    "Una",
    "Ubá",
    "Poá",
    "Luz",
    "Jaú",
    "Itu",
    "Uauá",
    "Tauá",
    "Sumé",
    "Sapé",
    "Orós",
  ],
  "Brunei": [
    "Bandar Seri Begawan",
    "Kuala Belait",
    "Seria",
    "Tutong",
    "Bangar",
  ],
  "Bulgaria": [
    "Sofia",
    "Plovdiv",
    "Varna",
    "Burgas",
    "Ruse",
    "Stara Zagora",
    "Pleven",
    "Sliven",
    "Lom",
    "Vidin",
    "Aytos",
    "Yambol",
    "Vratsa",
    "Troyan",
    "Shumen",
    "Popovo",
    "Pernik",
    "Lovech",
    "Dobrich",
    "Smolyan",
    "Samokov",
    "Razgrad",
    "Petrich",
    "Montana",
    "Haskovo",
    "Karlovo",
    "Gabrovo",
    "Chirpan",
    "Svishtov",
    "Dupnitsa",
  ],
  "Burkina Faso": [
    "Ouagadougou",
    "Bobo-Dioulasso",
    "Koudougou",
    "Banfora",
    "Ouahigouya",
    "Tô",
    "Pô",
    "Pa",
    "Réo",
    "Léo",
    "Gao",
    "Yako",
    "Toma",
    "Tita",
    "Kaya",
    "Dori",
    "Dano",
    "Bama",
    "Mani",
    "Zorgo",
    "Zabré",
    "Yalgo",
    "Titao",
    "Sabou",
    "Saaba",
    "Nouna",
    "Manga",
    "Kouka",
    "Kindi",
    "Gaoua",
  ],
  "Burundi": [
    "Bujumbura",
    "Gitega",
    "Muyinga",
    "Ngozi",
    "Ruyigi",
    "Vyanda",
    "Karusi",
    "Mpanda",
    "Rumonge",
    "Gatumba",
    "Bubanza",
    "Kayanza",
    "Kirundo",
    "Cibitoke",
    "Zanandore",
    "Cendajuru",
  ],
  "Cabo Verde": [
    "Praia",
    "Mindelo",
    "Santa Maria",
    "Assomada",
    "São Filipe",
    "Espargos",
  ],
  "Cambodia": [
    "Phnom Penh",
    "Siem Reap",
    "Battambang",
    "Sihanoukville",
    "Kampong Cham",
    "Kep",
    "Dar",
    "Takeo",
    "Suong",
    "Snuol",
    "Yeang",
    "Bavet",
    "Mémót",
    "Pursat",
    "Pailin",
    "Kratié",
    "Kampot",
    "Lumphat",
    "Dangkao",
    "Banlung",
    "Ta Khmau",
    "Sisophon",
    "Samraong",
    "Kandoeng",
    "Koh Kong",
    "Prey Veng",
    "Paoy Paet",
    "Svay Rieng",
    "Stung Treng",
    "Phumĭ Tnaôt",
  ],
  "Cameroon": [
    "Yaoundé",
    "Douala",
    "Garoua",
    "Bamenda",
    "Bafoussam",
    "Maroua",
    "Ngaoundéré",
    "Buea",
    "Wum",
    "Oku",
    "Tiko",
    "Okoa",
    "Mora",
    "Maga",
    "Loum",
    "Edéa",
    "Bogo",
    "Ndop",
    "Bali",
    "Tonga",
    "Pitoa",
    "Penja",
    "Obala",
    "Manjo",
    "Mamfe",
    "Makak",
    "Magba",
    "Limbe",
    "Lagdo",
    "Kumbo",
  ],
  "Canada": [
    "Ottawa",
    "Toronto",
    "Montreal",
    "Vancouver",
    "Calgary",
    "Edmonton",
    "Quebec",
    "Winnipeg",
    "Hamilton",
    "Kitchener",
    "London",
    "Victoria",
    "Halifax",
    "Ajax",
    "Alma",
    "Amos",
    "Hull",
    "Brant",
    "Delta",
    "Haney",
    "Laval",
    "Leduc",
    "Magog",
    "Rouge",
    "Sooke",
    "Lévis",
    "Annex",
    "Carey",
    "Aurora",
    "Barrie",
  ],
  "Chad": [
    "N'Djamena",
    "Moundou",
    "Sarh",
    "Abéché",
    "Doba",
    "Mao",
    "Laï",
    "Bol",
    "Ati",
    "Fada",
    "Adré",
    "Pala",
    "Maro",
    "Léré",
    "Kelo",
    "Goré",
    "Béré",
    "Iriba",
    "Mongo",
    "Kyabé",
    "Benoy",
    "Koumra",
    "Fianga",
    "Bousso",
    "Bongor",
    "Bokoro",
    "Biltine",
    "Bitkine",
    "Bébédja",
    "Am Timan",
  ],
  "Chile": [
    "Santiago",
    "Valparaiso",
    "Concepcion",
    "La Serena",
    "Antofagasta",
    "Temuco",
    "Rancagua",
    "Talca",
    "Arica",
    "Puerto Montt",
    "Tomé",
    "Lota",
    "Lebu",
    "Buin",
    "Rengo",
    "Renca",
    "Pucón",
    "Penco",
    "Paine",
    "Ñuñoa",
    "Maipú",
    "Lampa",
    "Cunco",
    "Angol",
    "Ancud",
    "Vilcún",
    "Vicuña",
    "Parral",
    "Ovalle",
    "Osorno",
  ],
  "China": [
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
    "Chengdu",
    "Tianjin",
    "Wuhan",
    "Xian",
    "Hangzhou",
    "Nanjing",
    "Chongqing",
    "Shenyang",
    "Harbin",
    "Kunming",
    "Qingdao",
    "Gar",
    "Lop",
    "Kax",
    "Ahu",
    "Zepu",
    "Quxu",
    "Bayi",
    "Arix",
    "Wusu",
    "Hami",
    "Emin",
    "Dure",
    "Aqsu",
    "Nima",
    "Yuxi",
  ],
  "Colombia": [
    "Bogotá",
    "Medellin",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Cúcuta",
    "Bucaramanga",
    "Pereira",
    "Santa Marta",
    "Ibagué",
    "Manizales",
    "Tame",
    "Tadó",
    "Mitú",
    "Cota",
    "Chía",
    "Yumbo",
    "Yopal",
    "Yondó",
    "Vélez",
    "Urrao",
    "Turbo",
    "Tunja",
    "Tuluá",
    "Supía",
    "Sucre",
    "Patía",
    "Pasto",
    "Padua",
    "Pacho",
  ],
  "Comoros": [
    "Moroni",
    "Moutsamoudou",
    "Fomboni",
    "Domoni",
    "Tsémbéhou",
  ],
  "Congo": [
    "Aru",
    "Sake",
    "Pepa",
    "Goma",
    "Buta",
    "Beni",
    "Kutu",
    "Boma",
    "Watsa",
    "Wamba",
    "Uvira",
    "Pweto",
    "Mweka",
    "Miabi",
    "Luebo",
    "Lubao",
    "Lodja",
    "Kindu",
    "Kayna",
    "Katwa",
    "Isiro",
    "Ilebo",
    "Djugu",
    "Demba",
    "Bunia",
    "Bumba",
    "Bondo",
    "Binga",
    "Bakwa",
    "Aketi",
  ],
  "Costa Rica": [
    "San José",
    "Alajuela",
    "Cartago",
    "Heredia",
    "Puntarenas",
    "Liberia",
    "Ipís",
    "Tejar",
    "Limón",
    "Cañas",
    "Purral",
    "Nicoya",
    "Colima",
    "Aserrí",
    "Quesada",
    "Patarrá",
    "Paraíso",
    "Esparza",
    "San Juan",
    "Guápiles",
    "Turrialba",
    "Siquirres",
    "San Pedro",
    "San Pablo",
    "San Diego",
    "Guadalupe",
    "Chacarita",
    "San Rafael",
    "San Miguel",
    "San Isidro",
  ],
  "Croatia": [
    "Zagreb",
    "Split",
    "Rijeka",
    "Osijek",
    "Zadar",
    "Pula",
    "Slavonski Brod",
    "Solin",
    "Sisak",
    "Požega",
    "Đakovo",
    "Centar",
    "Vukovar",
    "Šibenik",
    "Sesvete",
    "Samobor",
    "Čakovec",
    "Zaprešić",
    "Vinkovci",
    "Varaždin",
    "Bjelovar",
    "Karlovac",
    "Dubrovnik",
    "Koprivnica",
    "Liberpolis",
    "Velika Gorica",
  ],
  "Cuba": [
    "Havana",
    "Santiago de Cuba",
    "Camagüey",
    "Holguín",
    "Santa Clara",
    "Guantánamo",
    "Cienfuegos",
    "Moa",
    "Yara",
    "Rodas",
    "Regla",
    "Pilón",
    "Morón",
    "Minas",
    "Maisí",
    "Lajas",
    "Guisa",
    "Guane",
    "Cueto",
    "Colón",
    "Cerro",
    "Bauta",
    "Banes",
    "Vedado",
    "Perico",
    "Mariel",
    "Víbora",
    "Jobabo",
    "Jobabo",
    "Jaruco",
  ],
  "Cyprus": [
    "Nicosia",
    "Limassol",
    "Larnaca",
    "Paphos",
    "Famagusta",
    "Kyrenia",
    "Mórfou",
    "Égkomi",
    "Protaras",
    "Stróvolos",
    "Aglantziá",
    "Aradíppou",
    "Germasógeia",
    "Káto Polemídia",
    "Káto Lakatámeia",
  ],
  "Czechia": [
    "Prague",
    "Brno",
    "Ostrava",
    "Plzen",
    "Liberec",
    "Olomouc",
    "Ceske Budejovice",
    "Hradec Kralove",
    "Usti nad Labem",
    "Pardubice",
    "Krč",
    "Zlín",
    "Řepy",
    "Most",
    "Háje",
    "Cheb",
    "Žatec",
    "Tábor",
    "Slaný",
    "Písek",
    "Opava",
    "Nusle",
    "Louny",
    "Líšeň",
    "Libeň",
    "Krnov",
    "Kolín",
    "Kadaň",
    "Jičín",
    "Děčín",
  ],
  "Denmark": [
    "Copenhagen",
    "Aarhus",
    "Odense",
    "Aalborg",
    "Frederiksberg",
    "Esbjerg",
    "Randers",
    "Kolding",
    "Horsens",
    "Vejle",
    "Viby",
    "Køge",
    "Valby",
    "Tilst",
    "Skive",
    "Ishøj",
    "Greve",
    "Farum",
    "Århus",
    "Viborg",
    "Tønder",
    "Nyborg",
    "Holbæk",
    "Vanløse",
    "Rødovre",
    "Næstved",
    "Herning",
    "Avedøre",
    "Allerød",
    "Taastrup",
  ],
  "Djibouti": [
    "Djibouti",
    "Ali Sabieh",
    "Tadjourah",
    "Obock",
    "Dikhil",
    "Arta",
    "Tadjoura",
    "Ali Sabih",
  ],
  "Dominica": [
    "Roseau",
    "Portsmouth",
    "Mahaut",
    "Berekua",
    "Saint Joseph",
  ],
  "Dominican Republic": [
    "Santo Domingo",
    "Santiago de los Caballeros",
    "La Romana",
    "San Pedro de Macorís",
    "San Francisco de Macorís",
    "Puerto Plata",
    "Mao",
    "Moca",
    "Baní",
    "Azua",
    "Neiba",
    "Nagua",
    "Cotuí",
    "Bonao",
    "Salcedo",
    "Dajabón",
    "La Vega",
    "Tamboril",
    "Quisqueya",
    "Jarabacoa",
    "Esperanza",
    "Constanza",
    "Bayaguana",
    "Río Grande",
    "Punta Cana",
    "Cristo Rey",
    "Boca Chica",
    "Monte Plata",
    "Monte Llano",
    "Bella Vista",
  ],
  "Ecuador": [
    "Quito",
    "Guayaquil",
    "Cuenca",
    "Santo Domingo",
    "Machala",
    "Manta",
    "Ambato",
    "Portoviejo",
    "Loja",
    "Tena",
    "Puyo",
    "Sucre",
    "Piñas",
    "Macas",
    "Guabo",
    "Daule",
    "Chone",
    "Zamora",
    "Vinces",
    "Tulcán",
    "Pujilí",
    "Playas",
    "Pasaje",
    "Ibarra",
    "Balzar",
    "Salinas",
    "Quevedo",
    "Posorja",
    "Pelileo",
    "Otavalo",
  ],
  "Egypt": [
    "Cairo",
    "Alexandria",
    "Giza",
    "Shubra El Kheima",
    "Port Said",
    "Suez",
    "Luxor",
    "Aswan",
    "Mansoura",
    "El Mahalla El Kubra",
    "Tanta",
    "Assiut",
    "Ţūd",
    "Qūş",
    "Mūţ",
    "Aga",
    "Ţūkh",
    "Ţimā",
    "Talā",
    "Qina",
    "Qifţ",
    "Qahā",
    "Iţsā",
    "Esna",
    "Idkū",
    "Edfu",
    "Būsh",
    "Bibā",
    "Badr",
    "Badr",
  ],
  "El Salvador": [
    "San Salvador",
    "Santa Ana",
    "Soyapango",
    "San Miguel",
    "Nueva San Salvador",
    "La Unión",
    "Apopa",
    "Izalco",
    "Metapán",
    "Delgado",
    "Usulután",
    "Ilopango",
    "Acajutla",
    "Sonzacate",
    "Sonsonate",
    "Mejicanos",
    "Aguilares",
    "San Martín",
    "San Marcos",
    "Chalchuapa",
    "Ahuachapán",
    "San Vicente",
    "Santa Tecla",
    "La Libertad",
    "Cojutepeque",
    "Zacatecoluca",
    "Chalatenango",
    "Sensuntepeque",
    "San Francisco",
    "Quezaltepeque",
  ],
  "Equatorial Guinea": [
    "Malabo",
    "Bata",
    "Ebebiyín",
    "Acalayong",
    "Evinayong",
    "Ebebiyin",
    "Ciudad de la Paz",
  ],
  "Eritrea": [
    "Asmara",
    "Keren",
    "Massawa",
    "Assab",
    "Mendefera",
    "Himora",
    "Barentu",
  ],
  "Estonia": [
    "Tallinn",
    "Tartu",
    "Narva",
    "Pärnu",
    "Kohtla-Järve",
    "Viljandi",
    "Nõmme",
    "Pirita",
    "Maardu",
    "Lasnamäe",
    "Mustamäe",
    "Kesklinn",
    "Haabersti",
    "Kristiine",
    "Põhja-Tallinn",
  ],
  "Eswatini": [
    "Mbabane",
    "Manzini",
    "Big Bend",
    "Malkerns",
    "Nhlangano",
    "Lobamba",
  ],
  "Ethiopia": [
    "Addis Ababa",
    "Dire Dawa",
    "Mekelle",
    "Gondar",
    "Bahir Dar",
    "Hawassa",
    "Jimma",
    "Dessie",
    "Waal",
    "Waka",
    "Tēpī",
    "Sīrē",
    "Nejo",
    "Mojo",
    "Mīlē",
    "Metu",
    "Mena",
    "Leku",
    "Kele",
    "Gode",
    "Goba",
    "Raqo",
    "Gēdo",
    "Dolo",
    "Dīla",
    "Dēra",
    "Dayē",
    "Ciro",
    "Burē",
    "Batī",
  ],
  "Fiji": [
    "Suva",
    "Nadi",
    "Lautoka",
    "Labasa",
    "Ba",
    "Levuka",
    "Lami",
    "Nasinu",
    "Sigatoka",
  ],
  "Finland": [
    "Helsinki",
    "Espoo",
    "Tampere",
    "Vantaa",
    "Oulu",
    "Turku",
    "Jyväskylä",
    "Lahti",
    "Kuopio",
    "Pori",
    "Salo",
    "Kemi",
    "Vihti",
    "Vaasa",
    "Sibbo",
    "Rauma",
    "Raahe",
    "Nokia",
    "Lohja",
    "Lieto",
    "Kotka",
    "Jämsä",
    "Haaga",
    "Olari",
    "Tornio",
    "Raisio",
    "Loimaa",
    "Laukaa",
    "Kerava",
    "Kallio",
  ],
  "France": [
    "Paris",
    "Lyon",
    "Marseille",
    "Toulouse",
    "Nice",
    "Nantes",
    "Montpellier",
    "Strasbourg",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Saint-Étienne",
    "Le Havre",
    "Toulon",
    "Pau",
    "Hem",
    "Gap",
    "Dax",
    "Toul",
    "Sète",
    "Sens",
    "Riom",
    "Rezé",
    "Osny",
    "Orly",
    "Metz",
    "Lucé",
    "Loos",
    "Lens",
  ],
  "Gabon": [
    "Libreville",
    "Port-Gentil",
    "Franceville",
    "Oyem",
    "Moanda",
    "Oyam",
    "Ntoum",
    "Bitam",
    "Owendo",
    "Mouila",
    "Akanda",
    "Makokou",
    "Tchibanga",
    "Lambaréné",
    "Koulamoutou",
  ],
  "Gambia": [
    "Banjul",
    "Serekunda",
    "Brikama",
    "Bakau",
    "Farafenni",
    "Soma",
    "Kotu",
    "Tanji",
    "Lamin",
    "Abuko",
    "Sukuta",
    "Gunjur",
    "Farato",
    "Brufut",
    "Bakoti",
    "Sanyang",
    "Sanchaba",
    "Kanifing",
    "Ibo Town",
    "Welingara",
    "Kunkujang",
    "Busumbala",
    "Talinding",
    "Nema Kunku",
    "Faji Kunda",
    "Latri Kunda",
    "Dippa Kunda",
    "Manjai Kunda",
    "Latri Sabiji",
    "New Jeshwang",
  ],
  "Georgia": [
    "Tbilisi",
    "Kutaisi",
    "Batumi",
    "Rustavi",
    "Zugdidi",
    "Gori",
    "Poti",
    "Telavi",
    "Sokhumi",
    "Marneuli",
    "Kobuleti",
    "Khashuri",
    "Zestaponi",
    "Samtredia",
    "Ts’khinvali",
    "Akhaltsikhe",
    "Stantsiya Novyy Afon",
  ],
  "Germany": [
    "Berlin",
    "Munich",
    "Hamburg",
    "Cologne",
    "Frankfurt",
    "Stuttgart",
    "Düsseldorf",
    "Dortmund",
    "Leipzig",
    "Bremen",
    "Dresden",
    "Hannover",
    "Nuremberg",
    "Duisburg",
    "Ulm",
    "Hof",
    "Aue",
    "Werl",
    "Verl",
    "Unna",
    "Syke",
    "Suhl",
    "Selm",
    "Selb",
    "Roth",
    "Rees",
    "Olpe",
    "Much",
    "Marl",
    "Leer",
  ],
  "Ghana": [
    "Accra",
    "Kumasi",
    "Tamale",
    "Sekondi-Takoradi",
    "Ashaiman",
    "Sunyani",
    "Cape Coast",
    "Wa",
    "Ho",
    "Mim",
    "Osu",
    "Tepa",
    "Tema",
    "Tafo",
    "Keta",
    "Kade",
    "Foso",
    "Dome",
    "Esim",
    "Apam",
    "Yendi",
    "Yegyi",
    "Suhum",
    "Kasoa",
    "Hohoe",
    "Gbawe",
    "Goaso",
    "Elubo",
    "Ejura",
    "Bawku",
  ],
  "Greece": [
    "Athens",
    "Thessaloniki",
    "Patras",
    "Heraklion",
    "Larissa",
    "Volos",
    "Ioannina",
    "Chania",
    "Chalcis",
    "Serres",
    "Kavala",
    "Kos",
    "Vári",
    "Fylí",
    "Árta",
    "Voúla",
    "Pátra",
    "Ílion",
    "Lamía",
    "Chios",
    "Árgos",
    "Aígio",
    "Ródos",
    "Dráma",
    "Corfu",
    "Péfki",
    "Thívai",
    "Sparta",
    "Pýrgos",
    "Pérama",
  ],
  "Grenada": [
    "St. George's",
    "Gouyave",
    "Grenville",
    "Victoria",
    "Sauteurs",
    "Saint George's",
  ],
  "Guatemala": [
    "Guatemala City",
    "Mixco",
    "Villa Nueva",
    "Quetzaltenango",
    "Petapa",
    "San Juan Sacatepéquez",
    "Palín",
    "Nebaj",
    "Cobán",
    "Zacapa",
    "Soloma",
    "Sololá",
    "Salamá",
    "Poptún",
    "Patzún",
    "Panzos",
    "Jalapa",
    "Gualán",
    "Flores",
    "Chisec",
    "Cantel",
    "Salcajá",
    "Rabinal",
    "Patulul",
    "Nahualá",
    "Morales",
    "Masagua",
    "Jutiapa",
    "Cuilapa",
    "Colomba",
  ],
  "Guinea": [
    "Conakry",
    "Nzérékoré",
    "Kankan",
    "Kindia",
    "Labé",
    "Mamou",
    "Pita",
    "Lola",
    "Fria",
    "Boké",
    "Coyah",
    "Beyla",
    "Banko",
    "Tougué",
    "Kamsar",
    "Manéah",
    "Kamabi",
    "Douako",
    "Dixinn",
    "Dabola",
    "Siguiri",
    "Macenta",
    "Koumbia",
    "Faranah",
    "Dubréka",
    "Kolenté",
    "Dogomet",
    "Télimélé",
    "Mandiana",
    "Koundara",
  ],
  "Guinea-Bissau": [
    "Bissau",
    "Bafatá",
    "Gabú",
    "Bissorã",
    "Cacheu",
    "Belem",
    "Xitole",
    "Plaque",
    "Luanda",
    "Quelele",
    "Contumo",
    "Missira",
    "Sintra-Nema",
    "Santa-Luzia",
    "Bairro Militar",
    "Reino de Bandim",
    "Reino de Antula",
  ],
  "Guyana": [
    "Georgetown",
    "Linden",
    "New Amsterdam",
    "Anna Regina",
    "Bartica",
  ],
  "Haiti": [
    "Port-au-Prince",
    "Carrefour",
    "Delmas",
    "Cap-Haïtien",
    "Pétion-Ville",
    "Les Cayes",
    "Lenbe",
    "Tigwav",
    "Jacmel",
    "Hinche",
    "Léogâne",
    "Jérémie",
    "Kenscoff",
    "Gressier",
    "Grangwav",
    "Gonaïves",
    "Désarmes",
    "Arcahaie",
    "Verrettes",
    "Thomazeau",
    "Miragoâne",
    "Saint-Marc",
    "Dessalines",
    "Pétionville",
    "Port-de-Paix",
    "Grand Gosier",
    "Terrier Rouge",
    "Saint-Raphaël",
    "Fond Parisien",
    "Ti Port-de-Paix",
  ],
  "Honduras": [
    "Tegucigalpa",
    "San Pedro Sula",
    "La Ceiba",
    "Choloma",
    "El Progreso",
    "Comayagua",
    "Yoro",
    "Tela",
    "Sabá",
    "Omoa",
    "Tocoa",
    "Danlí",
    "Atima",
    "Yorito",
    "Sulaco",
    "La Paz",
    "Langue",
    "Iriona",
    "Lepaera",
    "La Lima",
    "Gualaco",
    "Esquías",
    "Corquín",
    "Arizona",
    "Victoria",
    "San Luis",
    "Morocelí",
    "Marcovia",
    "Cofradía",
    "Sonaguera",
  ],
  "Hungary": [
    "Budapest",
    "Debrecen",
    "Szeged",
    "Miskolc",
    "Pécs",
    "Győr",
    "Nyíregyháza",
    "Kecskemét",
    "Székesfehérvár",
    "Szombathely",
    "Ózd",
    "Vác",
    "Göd",
    "Fót",
    "Érd",
    "Makó",
    "Eger",
    "Tata",
    "Pest",
    "Pápa",
    "Paks",
    "Gyál",
    "Buda",
    "Baja",
    "Ajka",
    "Gyula",
    "Békés",
    "Abony",
    "Zugló",
    "Óbuda",
  ],
  "Iceland": [
    "Reykjavik",
    "Kópavogur",
    "Hafnarfjörður",
    "Akureyri",
    "Reykjanesbær",
    "Garðabær",
    "Keflavík",
    "Reykjavík",
  ],
  "India": [
    "New Delhi",
    "Mumbai",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    "Ūn",
    "Un",
    "Od",
    "Wai",
    "Una",
    "Una",
    "Ron",
    "Pen",
    "Nūh",
    "Ner",
    "Mūl",
    "Mon",
    "Mau",
    "Mau",
  ],
  "Indonesia": [
    "Jakarta",
    "Surabaya",
    "Bandung",
    "Bekasi",
    "Medan",
    "Tangerang",
    "Depok",
    "Semarang",
    "Palembang",
    "Makassar",
    "Yogyakarta",
    "Surakarta",
    "Denpasar",
    "Soe",
    "Weru",
    "Wedi",
    "Utan",
    "Ubud",
    "Tual",
    "Tiom",
    "Tayu",
    "Soko",
    "Raha",
    "Poso",
    "Pati",
    "Pare",
    "Palu",
    "Kuta",
    "Ende",
    "Dobo",
  ],
  "Iran": [
    "Nūr",
    "Qom",
    "Qīr",
    "Lār",
    "Jam",
    "Bam",
    "Yazd",
    "Veys",
    "Taft",
    "Shāl",
    "Sari",
    "Qods",
    "Oskū",
    "Nekā",
    "Maku",
    "Makū",
    "Lālī",
    "Kīsh",
    "Khūy",
    "Jask",
    "Īlām",
    "Fasā",
    "Evaz",
    "Bāft",
    "Bāfq",
    "Aznā",
    "Aznā",
    "Arāk",
    "Anār",
    "Āmol",
  ],
  "Iraq": [
    "Baghdad",
    "Basra",
    "Mosul",
    "Erbil",
    "Kirkuk",
    "Karbala",
    "Najaf",
    "Sulaymaniyah",
    "Hīt",
    "Zaxo",
    "Kufa",
    "Sīnah",
    "Kifrī",
    "Kelar",
    "Ḩarir",
    "Soran",
    "Dihok",
    "Bayjī",
    "Balad",
    "‘Afak",
    "Ākra",
    "‘Anah",
    "Tikrīt",
    "Sumayl",
    "Pīrmām",
    "Şafwān",
    "Rānyah",
    "Batifa",
    "Ramadi",
    "‘Aqrah",
  ],
  "Ireland": [
    "Dublin",
    "Cork",
    "Limerick",
    "Galway",
    "Waterford",
    "Drogheda",
    "Dundalk",
    "Swords",
    "Bray",
    "Navan",
    "Naas",
    "Sligo",
    "Lucan",
    "Ennis",
    "Tralee",
    "Carlow",
    "Wexford",
    "Leixlip",
    "Finglas",
    "Douglas",
    "Athlone",
    "Tallaght",
    "Maynooth",
    "Malahide",
    "Kilkenny",
    "Tullamore",
    "Celbridge",
    "Sandyford",
    "Portlaoise",
    "Greystones",
  ],
  "Italy": [
    "Rome",
    "Milan",
    "Naples",
    "Turin",
    "Palermo",
    "Genoa",
    "Bologna",
    "Florence",
    "Venice",
    "Bari",
    "Catania",
    "Verona",
    "Messina",
    "Padua",
    "Rho",
    "Bra",
    "Noto",
    "Gela",
    "Enna",
    "Todi",
    "Sora",
    "Sava",
    "Pisa",
    "Nola",
    "Noci",
    "Meda",
    "Lugo",
    "Lodi",
    "Lido",
    "Jesi",
  ],
  "Jamaica": [
    "Kingston",
    "Spanish Town",
    "Portmore",
    "Montego Bay",
    "Mandeville",
    "May Pen",
    "Linstead",
    "Ocho Rios",
    "Old Harbour",
    "New Kingston",
    "Barrett Town",
    "Half Way Tree",
    "Savanna-la-Mar",
  ],
  "Japan": [
    "Tokyo",
    "Osaka",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Kyoto",
    "Kawasaki",
    "Saitama",
    "Hiroshima",
    "Sendai",
    "Yokohama",
    "Chiba",
    "Ōi",
    "Yao",
    "Yae",
    "Uwa",
    "Uto",
    "Umi",
    "Uji",
    "Ube",
    "Tsu",
    "Ōzu",
    "Ōta",
    "Ono",
    "Ono",
    "Ōme",
    "Ōji",
    "Ōbu",
    "Mie",
  ],
  "Jordan": [
    "Amman",
    "Zarqa",
    "Irbid",
    "Russeifa",
    "Aqaba",
    "Mafraq",
    "Madaba",
    "Safi",
    "Saḩāb",
    "Māḩiş",
    "Ma'an",
    "‘Izrā",
    "Aydūn",
    "Mādabā",
    "Judita",
    "Jarash",
    "‘Ajlūn",
    "Rukban",
    "As Salţ",
    "‘Anjarah",
    "Qīr Moāv",
    "Ṣuwayliḥ",
    "Ar Ramthā",
    "Al Fuḩayş",
    "Kurayyimah",
    "Aţ Ţafīlah",
    "Karak City",
    "Wādī as Sīr",
    "Ḩayy Khildā",
    "Al Jubayhah",
  ],
  "Kazakhstan": [
    "Almaty",
    "Astana",
    "Shymkent",
    "Karagandy",
    "Aktobe",
    "Taraz",
    "Pavlodar",
    "Ust-Kamenogorsk",
    "Shu",
    "Oral",
    "Embi",
    "Esik",
    "Aksu",
    "Aksu",
    "Arys",
    "Aral",
    "Abay",
    "Abay",
    "Aktau",
    "Aqsay",
    "Altay",
    "Semey",
    "Saran",
    "Merke",
    "Atyrau",
    "Zaysan",
    "Tekeli",
    "Shelek",
    "Rudnyy",
    "Ridder",
  ],
  "Kenya": [
    "Nairobi",
    "Mombasa",
    "Kisumu",
    "Nakuru",
    "Eldoret",
    "Thika",
    "Malindi",
    "Kitale",
    "Garissa",
    "Kakamega",
    "Voi",
    "Mai",
    "Wote",
    "Tetu",
    "Ramu",
    "Molo",
    "Meru",
    "Maua",
    "Lamu",
    "Iten",
    "Hola",
    "Embu",
    "Juja",
    "Wajir",
    "Ruiru",
    "Rongo",
    "Nyeri",
    "Njoro",
    "Ngong",
    "Narok",
  ],
  "Kiribati": [
    "South Tarawa",
    "Betio",
    "Bairiki",
    "Bikenibeu",
    "Tabwakea",
    "Tarawa",
  ],
  "Kuwait": [
    "Kuwait City",
    "Hawalli",
    "Al Farwaniyah",
    "Al Ahmadi",
    "Salmiya",
    "Jahra",
    "Bayān",
    "Salwá",
    "Ḩawallī",
    "Ar Riqqah",
    "Al Manqaf",
    "Al Jahrā’",
    "Al Finţās",
    "Al Aḩmadī",
    "Ad Dasmah",
    "Al Faḩāḩīl",
    "Ar Rābiyah",
    "Al Mahbūlah",
    "As Sālimīyah",
    "Al Farwānīyah",
    "Ar Rumaythīyah",
    "Şabāḩ as Sālim",
    "Janūb as Surrah",
  ],
  "Kyrgyzstan": [
    "Bishkek",
    "Osh",
    "Jalal-Abad",
    "Karakol",
    "Tokmok",
    "Talas",
    "Kant",
    "Suzak",
    "Uzgen",
    "Naryn",
    "Massy",
    "Manas",
    "Iradan",
    "Nookat",
    "Batken",
    "Suluktu",
    "Razzakov",
    "Balykchy",
    "Kara Suu",
    "Ivanovka",
    "Ala-Buka",
    "Toktogul",
    "Kyzyl-Suu",
    "Kara-Kul’",
    "Tash-Kumyr",
    "Kyzyl-Kyya",
    "Kara-Balta",
    "Kara-Kulja",
    "Lebedinovka",
    "Kochkor-Ata",
  ],
  "Laos": [
    "Vientiane",
    "Savannakhet",
    "Pakse",
    "Luang Prabang",
    "Phonsavan",
    "Thakhek",
  ],
  "Latvia": [
    "Riga",
    "Daugavpils",
    "Liepāja",
    "Jelgava",
    "Jūrmala",
    "Ventspils",
    "Ogre",
    "Cēsis",
    "Tukums",
    "Mārupe",
    "Rēzekne",
    "Valmiera",
    "Salaspils",
    "Jēkabpils",
    "Dārzciems",
  ],
  "Lebanon": [
    "Beirut",
    "Tripoli",
    "Sidon",
    "Tyre",
    "Nabatieh",
    "Baalbek",
    "Aley",
    "Zahlé",
    "Byblos",
    "Aarsâl",
    "Jounieh",
    "Bsharri",
    "Ghazieh",
    "Chmistâr",
    "Habboûch",
    "El Hermel",
    "En Nâqoûra",
    "Ra’s Bayrūt",
    "Nabatîyé et Tahta",
  ],
  "Lesotho": [
    "Maseru",
    "Teyateyaneng",
    "Mafeteng",
    "Hlotse",
    "Mohale's Hoek",
    "Mabote",
    "Quthing",
    "Maputsoe",
    "Qacha’s Nek",
    "Butha-Buthe",
    "Thaba-Tseka",
  ],
  "Liberia": [
    "Monrovia",
    "Gbarnga",
    "Kakata",
    "Bensonville",
    "Harper",
    "Voinjama",
    "Ganta",
    "Zwedru",
    "Harbel",
    "Saclepea",
    "Buchanan",
    "New Yekepa",
    "Tubmanburg",
    "Greenville",
    "Pleebo City",
    "Foya Kamara",
    "Sanniquellie",
  ],
  "Libya": [
    "Tripoli",
    "Benghazi",
    "Misrata",
    "Tarhuna",
    "Al Khums",
    "Ajdabiya",
    "Sabha",
    "Hūn",
    "Brak",
    "Sirte",
    "Nālūt",
    "Ubari",
    "Tobruk",
    "Darnah",
    "At Tāj",
    "Zliten",
    "Yafran",
    "Şurmān",
    "Murzuk",
    "Mizdah",
    "Janzūr",
    "Zawiya",
    "Zintan",
    "Al Marj",
    "Al Jawf",
    "Zuwarah",
    "Tājūrā’",
    "Gharyan",
    "Shahhat",
    "Al Abyār",
  ],
  "Liechtenstein": [
    "Vaduz",
    "Schaan",
    "Triesen",
    "Balzers",
    "Triesenberg",
  ],
  "Lithuania": [
    "Vilnius",
    "Kaunas",
    "Klaipėda",
    "Šiauliai",
    "Panevėžys",
    "Alytus",
    "Utena",
    "Plunge",
    "Jonava",
    "Ukmerge",
    "Telsiai",
    "Taurage",
    "Palanga",
    "Pilaitė",
    "Šeškinė",
    "Kretinga",
    "Gargždai",
    "Eiguliai",
    "Lazdynai",
    "Vilkpėdė",
    "Visaginas",
    "Mazeikiai",
    "Kėdainiai",
    "Aleksotas",
    "Šilainiai",
    "Antakalnis",
    "Radviliskis",
    "Marijampolė",
    "Naujininkai",
    "Pašilaičiai",
  ],
  "Luxembourg": [
    "Luxembourg",
    "Esch-sur-Alzette",
    "Differdange",
    "Dudelange",
    "Ettelbruck",
  ],
  "Madagascar": [
    "Antananarivo",
    "Toamasina",
    "Mahajanga",
    "Fianarantsoa",
    "Toliara",
    "Antsiranana",
    "Didy",
    "Ivato",
    "Ihosy",
    "Sadabe",
    "Jafaro",
    "Ikongo",
    "Betafo",
    "Beloha",
    "Bekily",
    "Andapa",
    "Tsiombe",
    "Soalala",
    "Sambava",
    "Morombe",
    "Ivohibe",
    "Betroka",
    "Betioky",
    "Ambanja",
    "Vondrozo",
    "Vohipeno",
    "Vohipaho",
    "Tôlanaro",
    "Sakaraha",
    "Sahavato",
  ],
  "Malawi": [
    "Lilongwe",
    "Blantyre",
    "Mzimba",
    "Zomba",
    "Kasungu",
    "Mangochi",
    "Mzuzu",
    "Dedza",
    "Salima",
    "Rumphi",
    "Ntcheu",
    "Nsanje",
    "Mwanza",
    "Balaka",
    "Karonga",
    "Chitipa",
    "Mulanje",
    "Mponela",
    "Mchinji",
    "Liwonde",
    "Nkhotakota",
    "Nkhata Bay",
    "Monkey Bay",
  ],
  "Malaysia": [
    "Kuala Lumpur",
    "George Town",
    "Ipoh",
    "Shah Alam",
    "Petaling Jaya",
    "Johor Bahru",
    "Kota Kinabalu",
    "Kuching",
    "Malacca City",
    "Bau",
    "Sik",
    "SS2",
    "Kuah",
    "Raub",
    "Muar",
    "Paka",
    "Sibu",
    "Daro",
    "Niah",
    "Miri",
    "Ijok",
    "Jawi",
    "Maran",
    "Kulai",
    "Masai",
    "Pagoh",
    "Bakri",
    "Labis",
    "Kapar",
    "Klang",
  ],
  "Maldives": [
    "Malé",
    "Addu City",
    "Fuvahmulah",
    "Kulhudhuffushi",
    "Thinadhoo",
    "Male",
  ],
  "Mali": [
    "Bamako",
    "Sikasso",
    "Mopti",
    "Koutiala",
    "Ségou",
    "Kayes",
    "Gao",
    "San",
    "Bla",
    "Sibi",
    "Nara",
    "Koro",
    "Kita",
    "Kati",
    "Fana",
    "Diré",
    "Nioro",
    "Niono",
    "Kouri",
    "Kidal",
    "Diéma",
    "Bamba",
    "Zégoua",
    "Sagalo",
    "Mahina",
    "Kabala",
    "Djenné",
    "Dioïla",
    "Bourem",
    "Yorosso",
  ],
  "Malta": [
    "Valletta",
    "Birkirkara",
    "Qormi",
    "Mosta",
    "Żabbar",
    "St. Paul's Bay",
    "Sliema",
    "San Pawl il-Baħar",
  ],
  "Mauritania": [
    "Nouakchott",
    "Nouadhibou",
    "Néma",
    "Kaédi",
    "Rosso",
    "Zouérat",
    "Atar",
    "Aleg",
    "Ksar",
    "Kiffa",
    "Bogué",
    "Mbera",
    "Tékane",
    "Guerou",
    "Akjoujt",
    "Ṭinṭâne",
    "Sélibaby",
    "Elghabra",
    "Dar Naim",
    "Tembedgha",
    "El ’Ayoûn",
    "Bougadoum",
    "Boutilimitt",
    "Magṭa‘ Laḥjar",
    "Tevragh Zeina",
    "Ayoun El Atrous",
  ],
  "Mauritius": [
    "Port Louis",
    "Beau Bassin-Rose Hill",
    "Vacoas-Phoenix",
    "Curepipe",
    "Quatre Bornes",
    "Mahébourg",
    "Vacoas",
    "Triolet",
    "Bambous",
    "Goodlands",
    "Le Hochet",
    "Saint Pierre",
    "Centre de Flacq",
    "Baie du Tombeau",
    "Bel Air Rivière Sèche",
  ],
  "Mexico": [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Tijuana",
    "León",
    "Juárez",
    "Cancún",
    "Mexicali",
    "Acapulco",
    "Veracruz",
    "Mérida",
    "Chihuahua",
    "Culiacán",
    "Xico",
    "Xico",
    "Umán",
    "Peto",
    "Apan",
    "Isla",
    "Tala",
    "Nava",
    "Tulum",
    "Ticul",
    "Tecax",
    "Teapa",
    "Tetla",
    "Motul",
    "Ébano",
    "Álamo",
  ],
  "Moldova": [
    "Orhei",
    "Codru",
    "Cahul",
    "Bălţi",
    "Edineţ",
    "Soroca",
    "Comrat",
    "Bender",
    "Ungheni",
    "Rîbniţa",
    "Căuşeni",
    "Drochia",
    "Tiraspol",
    "Strășeni",
    "Slobozia",
    "Hînceşti",
    "Floreşti",
    "Durleşti",
    "Dubăsari",
    "Chisinau",
    "Ceadîr-Lunga",
    "Bilicenii Vechi",
  ],
  "Monaco": [
    "Monaco",
    "Monte Carlo",
    "La Condamine",
    "Fontvieille",
    "Moneghetti",
    "Monte-Carlo",
  ],
  "Mongolia": [
    "Ulaanbaatar",
    "Erdenet",
    "Darkhan",
    "Choibalsan",
    "Ölgii",
    "Ulaangom",
    "Bogd",
    "Khovd",
    "Altai",
    "Mörön",
    "Nalayh",
    "Darhan",
    "Bulgan",
    "Zuunmod",
    "Uliastay",
    "Dzuunmod",
    "Sühbaatar",
    "Saynshand",
    "Arvayheer",
    "Ulan Bator",
    "Tsetserleg",
    "Undurkhaan",
    "Dzüünharaa",
    "Baruun-Urt",
    "Bayanhongor",
    "Dalandzadgad",
  ],
  "Montenegro": [
    "Podgorica",
    "Nikšić",
    "Herceg Novi",
    "Pljevlja",
    "Budva",
    "Bijela",
    "Bar",
    "Cetinje",
    "Bijelo Polje",
  ],
                  "Morocco": [
    "Zag",
    "Beni-Mellal",
    "Tata",
    "Smara",
    "Kasba-Tadla",
    "Oujda-Ville",
    "Taza Hammou Meftah",
    "Marrakech",
    "Taroudant",
    "Errachidia",
    "Ouarzazate",
    "Bouarfa",
    "Jerrada",
    "Chefchaouen",
    "Tetuan / Sania Ramel",
    "Benguerir",
    "Nador-Aroui",
    "Khouribga",
    "Guelmin",
    "Tiznit",
    "Fes-Sais",
    "Sidi Slimane",
    "Meknes",
    "Ifrane",
    "Midelt",
    "Agadir Al Massira",
    "Laayoune",
    "Al Hoceima",
    "Safi",
    "Settat",
    "Nouasseur",
    "Agadir",
    "Saidia",
    "Kenitra",
    "Tan-Tan",
    "Larache",
    "Tanger Aerodrome",
    "El Jadida",
    "Rabat-Sale",
    "Dakhla",
    "Mohammedia",
    "Casablanca",
    "Sidi Ifni",
    "Essaouira",
  ],








  "Mozambique": [
    "Maputo",
    "Matola",
    "Beira",
    "Nampula",
    "Chimoio",
    "Nacala",
    "Quelimane",
    "Tete",
    "Caia",
    "Búzi",
    "Dondo",
    "Macia",
    "Songo",
    "Pemba",
    "Mueda",
    "Gurúè",
    "Boane",
    "Mocuba",
    "Chinde",
    "Pebane",
    "Monapo",
    "Maxixe",
    "Manica",
    "Cuamba",
    "Chokwé",
    "Chiúre",
    "Iapala",
    "Malema",
    "Ribáuè",
    "Xai-Xai",
  ],
  "Myanmar": [
    "Yangon",
    "Mandalay",
    "Naypyidaw",
    "Mawlamyine",
    "Bago",
    "Pathein",
    "Taunggyi",
    "Ye",
    "Waw",
    "Pyu",
    "Gwa",
    "Ann",
    "Ye-u",
    "Tamu",
    "Pyay",
    "Lewe",
    "Heho",
    "Okpo",
    "Zigon",
    "Zalun",
    "Dawei",
    "Pèkon",
    "Paung",
    "Mu-se",
    "Mudon",
    "Mogok",
    "Minbu",
    "Myeik",
    "Kayan",
    "Katha",
  ],
  "Namibia": [
    "Windhoek",
    "Rundu",
    "Walvis Bay",
    "Swakopmund",
    "Katima Mulilo",
    "Oshakati",
    "Gobabis",
    "Tsumeb",
    "Ndiyona",
    "Rehoboth",
    "Ondangwa",
    "Lüderitz",
    "Katutura",
    "Ongwediva",
    "Okahandja",
    "Otjiwarongo",
    "Keetmanshoop",
    "Grootfontein",
    "Helao Nafidi",
  ],
  "Nauru": [
    "Yaren",
    "Aiwo",
    "Boe",
    "Meneng",
    "Anibare",
  ],
  "Nepal": [
    "Kathmandu",
    "Pokhara",
    "Lalitpur",
    "Birgunj",
    "Biratnagar",
    "Janakpur",
    "Dharan",
    "Butwal",
    "Ilām",
    "Gaur",
    "Wāliṅ",
    "Pātan",
    "Lahān",
    "Tānsen",
    "Siraha",
    "Dharān",
    "Butwāl",
    "Banepā",
    "Bāgluṅ",
    "Ṭikāpur",
    "Hetauda",
    "Dailekh",
    "Birgañj",
    "Dipayal",
    "Panauti",
    "Inaruwa",
    "Triyuga",
    "Rājbirāj",
    "Gulariyā",
    "Dhankutā",
  ],
  "Netherlands": [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Tilburg",
    "Groningen",
    "Almere",
    "Breda",
    "Nijmegen",
    "Enschede",
    "Haarlem",
    "Urk",
    "Oss",
    "Epe",
    "Ede",
    "Velp",
    "Uden",
    "Tiel",
    "Leek",
    "Goes",
    "Elst",
    "Best",
    "Zeist",
    "Wisch",
    "Weesp",
    "Weert",
    "Vught",
    "Venlo",
    "Soest",
  ],
  "New Zealand": [
    "Wellington",
    "Auckland",
    "Christchurch",
    "Hamilton",
    "Tauranga",
    "Napier",
    "Dunedin",
    "Palmerston North",
    "Nelson",
    "Rotorua",
    "Whangarei",
    "Taupo",
    "Stoke",
    "Levin",
    "Otara",
    "Epsom",
    "Timaru",
    "Karori",
    "Massey",
    "Porirua",
    "Mangere",
    "Otahuhu",
    "Remuera",
    "Lincoln",
    "Richmond",
    "Hastings",
    "Avondale",
    "Gisborne",
    "Papakura",
    "Rangiora",
  ],
  "Nicaragua": [
    "Managua",
    "León",
    "Chinandega",
    "Masaya",
    "Matagalpa",
    "Estelí",
    "Granada",
    "Rama",
    "Siuna",
    "Rivas",
    "Boaco",
    "Somoto",
    "Ocotal",
    "Jalapa",
    "Mateare",
    "Corinto",
    "Camoapa",
    "Tipitapa",
    "Nandaime",
    "Nagarote",
    "Masatepe",
    "Juigalpa",
    "Jinotepe",
    "Jinotega",
    "El Viejo",
    "Diriamba",
    "Somotillo",
    "San Marcos",
    "Río Blanco",
    "El Crucero",
  ],
  "Niger": [
    "Niamey",
    "Zinder",
    "Maradi",
    "Agadez",
    "Tahoua",
    "Dosso",
    "Diffa",
    "Say",
    "Téra",
    "Gaya",
    "Kollo",
    "Gouré",
    "Arlit",
    "Aguié",
    "Torodi",
    "Tibiri",
    "Tanout",
    "Méhana",
    "Mayahi",
    "Illéla",
    "Dakoro",
    "Ayorou",
    "Abalak",
    "Nguigmi",
    "Mirriah",
    "Matamey",
    "Magaria",
    "Madaoua",
    "Gazaoua",
    "Tessaoua",
  ],
  "Nigeria": [
    "Abuja",
    "Lagos",
    "Kano",
    "Ibadan",
    "Benin City",
    "Port Harcourt",
    "Kaduna",
    "Enugu",
    "Aba",
    "Ilorin",
    "Jos",
    "Oyo",
    "Warri",
    "Uyo",
    "Uga",
    "Owo",
    "Ota",
    "Ode",
    "Iwo",
    "Itu",
    "Ifo",
    "Ibi",
    "Epe",
    "Ede",
    "Biu",
    "Aku",
    "Zuru",
    "Yola",
    "Ugep",
    "Soba",
  ],
  "North Korea": [
    "Pyongyang",
    "Hamhung",
    "Chongjin",
    "Nampo",
    "Wonsan",
    "Sinuiju",
    "Kaesong",
  ],
  "North Macedonia": [
    "Skopje",
    "Bitola",
    "Kumanovo",
    "Prilep",
    "Tetovo",
    "Ohrid",
    "Veles",
    "Čair",
    "Shtip",
    "Saraj",
    "Resen",
    "Debar",
    "Butel",
    "Zelino",
    "Vinica",
    "Tearce",
    "Struga",
    "Kičevo",
    "Radovis",
    "Lipkovo",
    "Kochani",
    "Delcevo",
    "Ilinden",
    "Strumica",
    "Negotino",
    "Negotino",
    "Gostivar",
    "Brvenica",
    "Kavadarci",
    "Kamenjane",
  ],
  "Norway": [
    "Oslo",
    "Bergen",
    "Trondheim",
    "Stavanger",
    "Drammen",
    "Fredrikstad",
    "Kristiansand",
    "Tromsø",
    "Sandnes",
    "Ålesund",
    "Bodø",
    "Alta",
    "Time",
    "Sola",
    "Moss",
    "Skien",
    "Molde",
    "Hamar",
    "Asker",
    "Larvik",
    "Horten",
    "Halden",
    "Gjøvik",
    "Nesttun",
    "Harstad",
    "Arendal",
    "Tønsberg",
    "Levanger",
    "Grimstad",
    "Sarpsborg",
  ],
  "Oman": [
    "Muscat",
    "Salalah",
    "Sohar",
    "Nizwa",
    "Sur",
    "Rustaq",
    "Ibri",
    "Bawshar",
    "Izkī",
    "Seeb",
    "Liwá",
    "Adam",
    "Şaḩam",
    "Nizwá",
    "‘Ibrī",
    "Ibrā’",
    "Shināş",
    "Khasab",
    "Bidbid",
    "Barkā’",
    "Bahlā’",
    "Yanqul",
    "Samā’il",
    "Şalālah",
    "Badīyah",
    "Qurayyāt",
    "As Suwayq",
    "Al Buraymī",
    "Al Khābūrah",
    "Sufālat Samā’il",
  ],
  "Pakistan": [
    "Islamabad",
    "Karachi",
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Multan",
    "Peshawar",
    "Quetta",
    "Hyderabad",
    "Gujranwala",
    "Sialkot",
    "Hub",
    "Zhob",
    "Topi",
    "Thul",
    "Tank",
    "Thal",
    "Sibi",
    "Moro",
    "Mach",
    "Lawa",
    "Johi",
    "Jhol",
    "Jand",
    "Hala",
    "Daur",
    "Dadu",
    "Chak",
    "Buni",
    "Bhan",
  ],
  "Palestine": [
    "Gaza",
    "Dūrā",
    "Rafaḩ",
    "Yaţţā",
    "Ţūbās",
    "Sa‘īr",
    "Janīn",
    "Idhnā",
    "Nablus",
    "Ḩalḩūl",
    "Battir",
    "Hebron",
    "Jabālyā",
    "Ţūlkarm",
    "Shu‘fāţ",
    "Balāţah",
    "‘Aţārūt",
    "Jericho",
    "Ramallah",
    "As Samū‘",
    "Al Yāmūn",
    "Al Bīrah",
    "Old City",
    "Al Burayj",
    "Qalqīlyah",
    "Qabāţīyah",
    "Bethlehem",
    "Bayt Jālā",
    "Khān Yūnis",
    "Bayt Lāhyā",
  ],
  "Panama": [
    "Panama City",
    "San Miguelito",
    "Tocumen",
    "David",
    "Colon",
    "Santiago de Veraguas",
    "La Chorrera",
    "Colón",
    "Ancón",
    "Cativá",
    "Curundú",
    "Veracruz",
    "Penonomé",
    "Pedregal",
    "Pedregal",
    "Chilibre",
    "Arraiján",
    "Sabanitas",
    "Río Abajo",
    "La Cabima",
    "Juan Díaz",
    "Las Cumbres",
    "Changuinola",
    "Nuevo Belén",
    "El Chorrillo",
    "Alcalde Díaz",
    "La Concepción",
    "Parque Lefevre",
  ],
  "Papua New Guinea": [
    "Port Moresby",
    "Lae",
    "Mount Hagen",
    "Madang",
    "Wewak",
    "Goroka",
    "Kokopo",
    "Daru",
    "Mendi",
    "Kimbe",
    "Arawa",
    "Bulolo",
    "Popondetta",
  ],
  "Paraguay": [
    "Asunción",
    "Ciudad del Este",
    "San Lorenzo",
    "Luque",
    "Capiatá",
    "Encarnación",
    "Lambaré",
    "Itá",
    "Pilar",
    "Nemby",
    "Limpio",
    "Yby Yaú",
    "Itauguá",
    "Caazapá",
    "Caacupé",
    "Caaguazú",
    "Villarrica",
    "Loma Plata",
    "Concepción",
    "Filadelfia",
    "Villa Hayes",
    "Villa Elisa",
    "San Antonio",
    "Coronel Oviedo",
    "San Juan Bautista",
    "Presidente Franco",
    "Fernando de la Mora",
    "Pedro Juan Caballero",
    "Mariano Roque Alonso",
  ],
  "Peru": [
    "Lima",
    "Arequipa",
    "Trujillo",
    "Chiclayo",
    "Piura",
    "Cusco",
    "Chimbote",
    "Iquitos",
    "Huancayo",
    "Tacna",
    "Ilo",
    "Ica",
    "Virú",
    "Saña",
    "Jaén",
    "Puno",
    "Mala",
    "Rioja",
    "Picsi",
    "Paita",
    "Moche",
    "Belen",
    "Yauri",
    "Tarma",
    "Pisco",
    "Nazca",
    "Junín",
    "Jauja",
    "Ilave",
    "Breña",
  ],
  "Philippines": [
    "Manila",
    "Quezon City",
    "Davao",
    "Cebu",
    "Zamboanga",
    "Cagayan de Oro",
    "Parañaque",
    "Dasmariñas",
    "Valenzuela",
    "Bacolod",
    "Iloilo City",
    "Cagayan de Oro",
    "Wao",
    "Pio",
    "Oas",
    "Iba",
    "Goa",
    "Bay",
    "Tupi",
    "Tiwi",
    "Taal",
    "Suay",
    "Pila",
    "Palo",
    "Paco",
    "Naic",
    "Naga",
    "Naga",
    "Mati",
    "Maco",
  ],
  "Poland": [
    "Warsaw",
    "Krakow",
    "Lodz",
    "Wroclaw",
    "Poznan",
    "Gdansk",
    "Szczecin",
    "Bydgoszcz",
    "Lublin",
    "Katowice",
    "Bialystok",
    "Gdynia",
    "Czestochowa",
    "Ełk",
    "Gaj",
    "Wola",
    "Pisz",
    "Łapy",
    "Żory",
    "Żary",
    "Śrem",
    "Reda",
    "Piła",
    "Nysa",
    "Łódź",
    "Łask",
    "Koło",
    "Kęty",
    "Huby",
    "Ząbki",
  ],
  "Portugal": [
    "Lisbon",
    "Porto",
    "Braga",
    "Coimbra",
    "Funchal",
    "Setúbal",
    "Amadora",
    "Aveiro",
    "Faro",
    "Madeira",
    "Leiria",
    "Vila Nova de Gaia",
    "Beja",
    "Ovar",
    "Maia",
    "Fafe",
    "Tomar",
    "Olhão",
    "Moita",
    "Loulé",
    "Lagos",
    "Évora",
    "Cacém",
    "Belém",
    "Belas",
    "Amora",
    "Algés",
    "Viseu",
    "Vilar",
    "Trofa",
  ],
  "Qatar": [
    "Doha",
    "Al Rayyan",
    "Al Wakrah",
    "Umm Salal",
    "Al Khor",
    "Al Daayen",
    "Al Shamal",
    "Lusail",
    "As Sadd",
    "Nu‘ayjah",
    "Al Khawr",
    "Ar Rayyān",
    "An Najmah",
    "Al Ghānim",
    "Umm Lakhbā",
    "Al ‘Unayzah",
    "Al Manşūrah",
    "Az̧ Z̧a‘āyin",
    "Farīj Kulayb",
    "Farīj al Amīr",
    "Umm Ghuwaylīnah",
    "Madīnat Khalīfah",
    "Al Maţār al ‘Atīq",
    "Umm Şalāl Muḩammad",
    "As Sulţah al Jadīdah",
    "Ath Thumāmah Khamsūn",
    "Al Hilāl al Gharbīyah",
    "Al Hilāl ash Sharqīyah",
    "Mu‘aydhir Rawḑat Rāshid",
    "Ath Thumāmah Sab‘ah wa Arba‘ūn",
  ],
  "Romania": [
    "Bucharest",
    "Cluj-Napoca",
    "Timișoara",
    "Iași",
    "Constanța",
    "Craiova",
    "Brașov",
    "Galați",
    "Ploiești",
    "Oradea",
    "Arad",
    "Dej",
    "Iaşi",
    "Huşi",
    "Deva",
    "Brad",
    "Blaj",
    "Balş",
    "Aiud",
    "Zalău",
    "Turda",
    "Sibiu",
    "Sebeş",
    "Roman",
    "Motru",
    "Mizil",
    "Lugoj",
    "Luduş",
    "Cugir",
    "Carei",
  ],
  "Russia": [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Kazan",
    "Nizhny Novgorod",
    "Chelyabinsk",
    "Samara",
    "Omsk",
    "Rostov-on-Don",
    "Ufa",
    "Krasnoyarsk",
    "Voronezh",
    "Perm",
  ],
  "Rwanda": [
    "Kigali",
    "Butare",
    "Gitarama",
    "Ruhengeri",
    "Gisenyi",
    "Kibuye",
    "Kora",
    "Nzega",
    "Ndera",
    "Cyato",
    "Mugina",
    "Shangi",
    "Byumba",
    "Busogo",
    "Gitesi",
    "Macuba",
    "Kagano",
    "Nyanza",
    "Musanze",
    "Ruhango",
    "Muhanga",
    "Kirimbi",
    "Kibungo",
    "Kirambo",
    "Rangiro",
    "Mukingo",
    "Kayonza",
    "Karambi",
    "Nyamata",
    "Gihombo",
  ],
  "Saint Kitts and Nevis": [
    "Basseterre",
    "Charlestown",
    "Dieppe Bay Town",
    "Sandy Point",
    "Cayon",
  ],
  "Saint Lucia": [
    "Castries",
    "Soufrière",
    "Vieux Fort",
    "Micoud",
    "Gros Islet",
    "Dennery",
  ],
  "Saint Vincent and the Grenadines": [
    "Kingstown",
    "Georgetown",
    "Barrouallie",
    "Port Elizabeth",
    "Chateaubelair",
    "Calliaqua",
  ],
  "Samoa": [
    "Apia",
    "Vaitele",
    "Faleula",
    "Malie",
    "Siusega",
  ],
  "San Marino": [
    "San Marino",
    "Borgo Maggiore",
    "Serravalle",
    "Domagnano",
    "Fiorentino",
  ],
  "Sao Tome and Principe": [
    "São Tomé",
    "Santo Amaro",
    "Neves",
    "Santana",
    "Trindade",
  ],
  "Saudi Arabia": [
    "Riyadh",
    "Jeddah",
    "Mecca",
    "Medina",
    "Dammam",
    "Khobar",
    "Tabuk",
    "Buraidah",
    "Khamis Mushait",
    "Abha",
    "Hail",
    "Jubail",
    "Yanbu",
    "Taif",
    "Ḩaql",
    "Duba",
    "Arar",
    "Afif",
    "Umluj",
    "Tārūt",
    "Şafwá",
    "Şabyā",
    "Rumāḩ",
    "Laylá",
    "Jizan",
    "Ha'il",
    "Ḑamad",
    "Ta’if",
    "‘Inak",
    "Bariq",
  ],
  "Senegal": [
    "Dakar",
    "Touba",
    "Thiès",
    "Rufisque",
    "Saint-Louis",
    "Kaolack",
    "Mbacké",
    "Ziguinchor",
    "Pout",
    "Joal",
    "Dara",
    "Sali",
    "Tiébo",
    "Mékhé",
    "Mbour",
    "Mboro",
    "Mbaké",
    "Matam",
    "Louga",
    "Kolda",
    "Kayar",
    "Kanel",
    "Pikine",
    "Ndioum",
    "Kahone",
    "Fatick",
    "Dagana",
    "Bargny",
    "Bambey",
    "Sédhiou",
  ],
  "Serbia": [
    "Belgrade",
    "Novi Sad",
    "Niš",
    "Kragujevac",
    "Subotica",
    "Prizren",
    "Kraljevo",
    "Zrenjanin",
    "Bor",
    "Ruma",
    "Zemun",
    "Vršac",
    "Senta",
    "Pirot",
    "Čačak",
    "Bečej",
    "Vrbas",
    "Užice",
    "Šabac",
    "Futog",
    "Vranje",
    "Inđija",
    "Sombor",
    "Apatin",
    "Zaječar",
    "Pančevo",
    "Negotin",
    "Kikinda",
    "Ćuprija",
    "Valjevo",
  ],
  "Seychelles": [
    "Victoria",
    "Anse Boileau",
    "Beau Vallon",
    "Takamaka",
    "Cascade",
  ],
  "Sierra Leone": [
    "Freetown",
    "Bo",
    "Kenema",
    "Makeni",
    "Koidu",
    "Port Loko",
    "Njala",
    "Bumpe",
    "Lunsar",
    "Kabala",
    "Mile 91",
    "Waterloo",
    "Segbwema",
    "Goderich",
  ],
  "Singapore": [
    "Singapore",
    "Bedok",
    "Ang Mo Kio",
    "Tampines",
    "Woodlands",
    "Hougang",
    "Jurong",
    "Eunos",
    "Fajar",
    "Senja",
    "Loyang",
    "Novena",
    "Jelebu",
    "Yew Tee",
    "Thomson",
    "Tanglin",
    "Punggol",
    "Kallang",
    "Geylang",
    "Kangkar",
    "Saujana",
    "Bangkit",
    "Hong Kah",
    "Boon Lay",
    "Ulu Bedok",
    "Serangoon",
    "Marsiling",
    "Kembangan",
    "Teck Whye",
    "Paya Lebar",
  ],
  "Slovakia": [
    "Bratislava",
    "Košice",
    "Prešov",
    "Žilina",
    "Banská Bystrica",
    "Nitra",
    "Trnava",
    "Martin",
    "Šaľa",
    "Snina",
    "Sereď",
    "Senec",
    "Čadca",
    "Poprad",
    "Zvolen",
    "Senica",
    "Púchov",
    "Levice",
    "Brezno",
    "Rožňava",
    "Humenné",
    "Vrakuňa",
    "Trenčín",
    "Skalica",
    "Pezinok",
    "Malacky",
    "Lučenec",
    "Komárno",
    "Komárno",
    "Galanta",
  ],
  "Slovenia": [
    "Ljubljana",
    "Maribor",
    "Celje",
    "Kranj",
    "Koper",
    "Velenje",
    "Novo Mesto",
    "Ptuj",
    "Trbovlje",
  ],
  "Solomon Islands": [
    "Honiara",
    "Auki",
    "Gizo",
    "Kirakira",
    "Lata",
    "Buala",
    "Vura",
    "Nggosi",
    "Kola'a",
    "Tandai",
    "Malango",
    "Panatina",
  ],
  "Somalia": [
    "Mogadishu",
    "Hargeisa",
    "Burao",
    "Kismayo",
    "Merca",
    "Baidoa",
    "Bosaso",
    "Eyl",
    "Ruqi",
    "Luuq",
    "Baki",
    "Marka",
    "Jilib",
    "Saaxo",
    "Saylac",
    "Jawhar",
    "Dhamas",
    "Borama",
    "Dhabad",
    "Qandala",
    "Jamaame",
    "Gebiley",
    "Garoowe",
    "Bu’aale",
    "Berbera",
    "Afgooye",
    "Hargeysa",
    "El Dibir",
    "Diinsoor",
    "Wanlaweyn",
  ],
  "South Africa": [
    "Pretoria",
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Port Elizabeth",
    "Bloemfontein",
    "East London",
    "Nelspruit",
    "Polokwane",
    "Kimberley",
    "Pietermaritzburg",
    "Upington",
    "Ugie",
    "Cala",
    "Vrede",
    "Sabie",
    "Reitz",
    "Parys",
    "Nigel",
    "Kriel",
    "Qonce",
    "Khowa",
    "Brits",
    "Alice",
    "Paarl",
    "Ceres",
    "Phola",
    "Welkom",
    "Verena",
    "Ulundi",
  ],
  "South Korea": [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Suwon",
    "Ulsan",
    "Jeonju",
    "Cheongju",
    "Changwon",
    "Ansan",
  ],
  "South Sudan": [
    "Juba",
    "Wau",
    "Malakal",
    "Yambio",
    "Bor",
    "Bentiu",
    "Yei",
    "Tonj",
    "Leer",
    "Aweil",
    "Torit",
    "Pajok",
    "Rumbek",
    "Winejok",
    "Kuacjok",
    "Gogrial",
    "Kafia Kingi",
  ],
  "Spain": [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Zaragoza",
    "Malaga",
    "Murcia",
    "Palma",
    "Bilbao",
    "Alicante",
    "Cordoba",
    "Valladolid",
    "Vigo",
    "Granada",
    "A Coruña",
    "Maó",
    "Ibi",
    "Vic",
    "Tui",
    "Teo",
    "Tías",
    "Rota",
    "Onda",
    "Mula",
    "Loja",
    "Lepe",
    "Jaén",
    "Inca",
    "Elda",
    "Coín",
  ],
  "Sri Lanka": [
    "Colombo",
    "Dehiwala-Mount Lavinia",
    "Moratuwa",
    "Sri Jayawardenepura Kotte",
    "Kandy",
    "Galle",
    "Jaffna",
    "Negombo",
    "Matara",
    "Matale",
    "Mannar",
    "Ja Ela",
    "Hatton",
    "Chilaw",
    "Ampara",
    "Wattala",
    "Vakarai",
    "Kegalle",
    "Kandana",
    "Hendala",
    "Gampola",
    "Bentota",
    "Badulla",
    "Welisara",
    "Weligama",
    "Vavuniya",
    "Puttalam",
    "Pottuvil",
    "Panadura",
    "Kelaniya",
  ],
  "Sudan": [
    "Khartoum",
    "Omdurman",
    "Khartoum North",
    "Nyala",
    "Port Sudan",
    "Kassala",
    "El Obeid",
    "Wad Madani",
    "Kas",
    "Doka",
    "Tokār",
    "Singa",
    "Rabak",
    "Kutum",
    "Kosti",
    "Burām",
    "Bārah",
    "Abyei",
    "Tullus",
    "Sinkat",
    "Shendi",
    "Suakin",
    "Sennar",
    "Rufā‘a",
    "Mellit",
    "Kināna",
    "Jubayt",
    "Berber",
    "Atbara",
    "Al-Fāw",
  ],
  "Suriname": [
    "Paramaribo",
    "Lelydorp",
    "Nieuw Nickerie",
    "Moengo",
    "Wanica",
    "Albina",
    "Flora",
    "Latour",
    "Tammenga",
    "Rainville",
    "Blauwgrond",
    "Welgelegen",
    "Beekhuizen",
    "Pontbuiten",
    "Weg naar Zee",
    "Munder Buiten",
  ],
  "Sweden": [
    "Stockholm",
    "Gothenburg",
    "Malmö",
    "Uppsala",
    "Västerås",
    "Örebro",
    "Linköping",
    "Helsingborg",
    "Jönköping",
    "Norrköping",
    "Lund",
    "Umeå",
    "Boo",
    "Täby",
    "Piteå",
    "Luleå",
    "Boden",
    "Ystad",
    "Visby",
    "Växjö",
    "Tumba",
    "Solna",
    "Nacka",
    "Lerum",
    "Kumla",
    "Kinna",
    "Gävle",
    "Falun",
    "Eslöv",
    "Borås",
  ],
  "Switzerland": [
    "Bern",
    "Zurich",
    "Geneva",
    "Basel",
    "Lausanne",
    "Winterthur",
    "Lucerne",
    "St. Gallen",
    "Lugano",
    "Fribourg",
    "Thun",
    "Chur",
    "Zug",
    "Wil",
    "Onex",
    "Nyon",
    "Jona",
    "Cham",
    "Baar",
    "Vevey",
    "Uster",
    "Pully",
    "Olten",
    "Köniz",
    "Emmen",
    "Bulle",
    "Baden",
    "Aarau",
    "Lancy",
    "Zürich",
  ],
  "Syria": [
    "Damascus",
    "Aleppo",
    "Homs",
    "Hama",
    "Latakia",
    "Raqqa",
    "Deir ez-Zor",
    "Idlib",
  ],
  "Taiwan": [
    "Daxi",
    "Buzi",
    "Puli",
    "Bade",
    "Lugu",
    "Xihu",
    "Budai",
    "Pitou",
    "Neili",
    "Neihu",
    "Yilan",
    "Jinhu",
    "Xiluo",
    "Xizhi",
    "Erlun",
    "Erlin",
    "Douliu",
    "Yujing",
    "Yingge",
    "Wufeng",
    "Citong",
    "Caotun",
    "Toufen",
    "Taipei",
    "Taibao",
    "Tainan",
    "Shulin",
    "Shetou",
    "Sanxia",
    "Sanzhi",
  ],
  "Tajikistan": [
    "Dushanbe",
    "Khujand",
    "Bokhtar",
    "Kulob",
    "Istaravshan",
    "Panjakent",
    "Vahdat",
    "Yovon",
    "Norak",
    "Kŭlob",
    "Hisor",
    "Hulbuk",
    "Vakhsh",
    "Muchun",
    "Chubek",
    "Isfara",
    "Buston",
    "Farkhor",
    "Khorugh",
    "Danghara",
    "Zarhalol",
    "Istiqlol",
    "Proletar",
    "Ishqoshim",
    "Qayroqqum",
    "Konibodom",
    "Shahriston",
    "Tursunzoda",
    "Moskovskiy",
    "Kolkhozobod",
  ],
  "Tanzania": [
    "Wete",
    "Same",
    "Puma",
    "Magu",
    "Vwawa",
    "Uyovu",
    "Tumbi",
    "Tinde",
    "Tanga",
    "Nzega",
    "Ngudu",
    "Ngara",
    "Moshi",
    "Mlowo",
    "Mlalo",
    "Mbulu",
    "Mbeya",
    "Matui",
    "Matai",
    "Maswa",
    "Laela",
    "Kyela",
    "Izazi",
    "Itigi",
    "Isaka",
    "Ilula",
    "Geita",
    "Geiro",
    "Chato",
    "Chala",
  ],
  "Thailand": [
    "Bangkok",
    "Chiang Mai",
    "Pattaya",
    "Phuket",
    "Hat Yai",
    "Nakhon Ratchasima",
    "Chonburi",
    "Udon Thani",
    "Ubon Ratchathani",
    "Nakhon Si Thammarat",
    "Khon Kaen",
    "Surat Thani",
    "Tak",
    "Nan",
    "Yala",
    "Trat",
    "Seka",
    "Loei",
    "Trang",
    "Thoen",
    "Krabi",
    "Kathu",
    "Surin",
    "Satun",
    "Sadao",
    "Ranot",
    "Phrae",
    "Dusit",
    "Na Di",
    "Ranong",
  ],
  "Togo": [
    "Lomé",
    "Sokodé",
    "Kara",
    "Kpalimé",
    "Atakpamé",
    "Dapaong",
    "Tsévié",
    "Anié",
    "Vogan",
    "Notsé",
    "Mango",
    "Badou",
    "Aného",
    "Bassar",
    "Bafilo",
    "Tchamba",
    "Tabligbo",
    "Sinkassé",
    "Sotouboua",
    "Niamtougou",
  ],
  "Tonga": [
    "Nuku'alofa",
    "Neiafu",
    "Pangai",
    "Hihifo",
    "Haveluloto",
    "Nuku‘alofa",
  ],
  "Trinidad and Tobago": [
    "Chaguanas",
    "Mon Repos",
    "San Fernando",
    "Port of Spain",
    "Arima",
    "Point Fortin",
    "Tunapuna",
    "Paradise",
    "Rio Claro",
    "Marabella",
    "Laventille",
    "Scarborough",
    "Diego Martin",
    "Sangre Grande",
  ],
  "Tunisia": [
    "Tunis",
    "Sfax",
    "Sousse",
    "Kairouan",
    "Bizerte",
    "Gabès",
    "Ariana",
    "Monastir",
    "La Marsa",
    "Douz",
    "Béja",
    "Ajim",
    "Tinja",
    "Thala",
    "Radès",
    "Korba",
    "Gafsa",
    "Nefta",
    "Tozeur",
    "Sukrah",
    "Skanes",
    "Kebili",
    "Nabeul",
    "Midoun",
    "Mateur",
    "Msaken",
    "Mareth",
    "Zarzis",
    "Zouila",
    "Chebba",
  ],
  "Turkey": [
    "Ankara",
    "Istanbul",
    "Izmir",
    "Bursa",
    "Adana",
    "Gaziantep",
    "Konya",
    "Antalya",
    "Kayseri",
    "Mersin",
    "Eskisehir",
    "Kocaeli",
    "Samsun",
  ],
  "Turkmenistan": [
    "Ashgabat",
    "Türkmenabat",
    "Daşoguz",
    "Mary",
    "Bayramaly",
    "Abadan",
    "Kaka",
    "Änew",
    "Jebel",
    "Oýrat",
    "Tejen",
    "Seydi",
    "Saýat",
    "Halaç",
    "Kerki",
    "Gumdag",
    "Sarahs",
    "Çaşgyn",
    "Gökdepe",
    "Bereket",
    "Yylanly",
    "Gubadag",
    "Görogly",
    "Yolöten",
    "Gazojak",
    "Arkadag",
    "Bäherden",
    "Magdanly",
    "Boldumsaz",
    "Balkanabat",
  ],
  "Tuvalu": [
    "Funafuti",
    "Vaiaku",
    "Asau",
    "Motufoua",
    "Gardner",
  ],
  "Uganda": [
    "Kampala",
    "Gulu",
    "Lira",
    "Mbarara",
    "Jinja",
    "Mbale",
    "Masaka",
    "Entebbe",
    "Moyo",
    "Kumi",
    "Kira",
    "Kazo",
    "Arua",
    "Apac",
    "Abim",
    "Opit",
    "Yumbe",
    "Njeru",
    "Ngora",
    "Nebbi",
    "Mpigi",
    "Hoima",
    "Gombe",
    "Busia",
    "Bombo",
    "Anaka",
    "Wakiso",
    "Tororo",
    "Soroti",
    "Rutoma",
  ],
  "Ukraine": [
    "Kyiv",
    "Kharkiv",
    "Odessa",
    "Dnipro",
    "Donetsk",
    "Zaporizhzhia",
    "Lviv",
    "Kryvyi Rih",
    "Mykolaiv",
    "Luhansk",
    "Vinnytsia",
    "Kherson",
    "Bar",
    "Uman",
    "Sumy",
    "Saki",
    "Reni",
    "Klov",
    "Yalta",
    "Terny",
    "Sudak",
    "Stryi",
    "Sokal",
    "Smila",
    "Sarny",
    "Romny",
    "Rivne",
    "Podil",
    "Ihren",
    "Odesa",
  ],
  "United Arab Emirates": [
    "Abu Dhabi",
    "Dubai",
    "Sharjah",
    "Al Ain",
    "Ajman",
    "Ras Al Khaimah",
    "Fujairah",
    "Umm Al Quwain",
    "Dibba",
    "Ghayathi",
    "Nāyf",
    "Kalbā",
    "Ḩattā",
    "Dayrah",
    "Mirdif",
    "Halwan",
    "Lahbab",
    "Warīsān",
    "Jumayrā",
    "Al Wasl",
    "Mankhūl",
    "Al Safa",
    "Al Jurf",
    "Abū Hayl",
    "Al Majaz",
    "Musaffah",
    "Ar Ruways",
    "Adh Dhayd",
    "As Saţwah",
    "Al Waheda",
  ],
  "United Kingdom": [
    "London",
    "Manchester",
    "Birmingham",
    "Leeds",
    "Glasgow",
    "Liverpool",
    "Bristol",
    "Edinburgh",
    "Cardiff",
    "Belfast",
    "Nottingham",
    "Sheffield",
    "Leicester",
    "Coventry",
    "Bradford",
    "Newcastle upon Tyne",
    "Ely",
    "Bow",
    "Ayr",
    "York",
    "Yate",
    "Yarm",
    "Ware",
    "Sale",
    "Ryde",
    "Rhyl",
    "Leek",
    "Hyde",
    "Hove",
    "Hook",
  ],
  "United States": [
    "Washington",
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Miami",
    "Jacksonville",
    "Columbus",
    "Charlotte",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Boston",
    "Nashville",
    "Detroit",
    "Atlanta",
    "Portland",
    "Ada",
    "Rye",
    "Roy",
    "Troy",
    "Shaw",
    "Bear",
  ],
  "Uruguay": [
    "Montevideo",
    "Salto",
    "Paysandú",
    "Las Piedras",
    "Rivera",
    "Melo",
    "Tacuarembó",
    "Young",
    "Rocha",
    "Pando",
    "Minas",
    "La Paz",
    "Florida",
    "Durazno",
    "Dolores",
    "Carmelo",
    "Artigas",
    "Trinidad",
    "Progreso",
    "Mercedes",
    "Maldonado",
    "Canelones",
    "San Carlos",
    "Santa Lucía",
    "Fray Bentos",
    "Treinta y Tres",
    "Barros Blancos",
    "Delta del Tigre",
    "San José de Mayo",
    "Paso de Carrasco",
  ],
  "Uzbekistan": [
    "Tashkent",
    "Namangan",
    "Samarkand",
    "Andijan",
    "Bukhara",
    "Nukus",
    "Qarshi",
    "Fergana",
    "Pop",
    "Xiva",
    "Oyim",
    "Quva",
    "Kitob",
    "Koson",
    "Denov",
    "Zafar",
    "Uychi",
    "Salor",
    "Asaka",
    "Chust",
    "Bo‘ka",
    "Tirmiz",
    "G‘uzor",
    "Chelak",
    "Boysun",
    "Oqtosh",
    "Yaypan",
    "Shovot",
    "Qo‘qon",
    "Nurota",
  ],
  "Vanuatu": [
    "Port Vila",
    "Luganville",
    "Isangel",
    "Sola",
    "Lakatoro",
    "Port-Vila",
  ],
  "Vatican City": [
    "Vatican City",
  ],
  "Venezuela": [
    "Cúa",
    "Coro",
    "Aroa",
    "Anaco",
    "Ureña",
    "Upata",
    "Tovar",
    "Tabay",
    "Colón",
    "Rubio",
    "Morón",
    "Guama",
    "Ejido",
    "Duaca",
    "Cagua",
    "Araya",
    "Zaraza",
    "Yumare",
    "Valera",
    "Tucaní",
    "Tinaco",
    "Táriba",
    "Socopó",
    "Sanare",
    "Quíbor",
    "Píritu",
    "Petare",
    "Pampán",
    "Ospino",
    "Nirgua",
  ],
  "Vietnam": [
    "Hanoi",
    "Ho Chi Minh City",
    "Da Nang",
    "Haiphong",
    "Huế",
    "Nha Trang",
    "Can Tho",
    "Bien Hoa",
    "Hue",
    "Vung Tau",
    "Hai Duong",
    "Quy Nhon",
  ],
  "Yemen": [
    "Sana'a",
    "Aden",
    "Taiz",
    "Al Hudaydah",
    "Ibb",
    "Mukalla",
    "Saada",
    "Dhamar",
    "Ataq",
    "Zabīd",
    "Yarīm",
    "Sanaa",
    "Saḩar",
    "Laḩij",
    "Bājil",
    "Mocha",
    "Sayyān",
    "Sa'dah",
    "Ma'rib",
    "Ḩajjah",
    "Dhamār",
    "‘Amrān",
    "Al Ḩazm",
    "Zinjibār",
    "Al Bayda",
    "Al Ḩudaydah",
    "Dhī as Sufāl",
    "Bayt al Faqīh",
    "Ghayl Bā Wazīr",
  ],
  "Zambia": [
    "Lusaka",
    "Ndola",
    "Kitwe",
    "Kabwe",
    "Chingola",
    "Mufulira",
    "Livingstone",
    "Kasama",
    "Mbala",
    "Sinda",
    "Mpika",
    "Monze",
    "Mongu",
    "Mansa",
    "Kaoma",
    "Kafue",
    "Isoka",
    "Choma",
    "Kaputa",
    "Samfya",
    "Nyimba",
    "Mumbwa",
    "Mkushi",
    "Maamba",
    "Lukulu",
    "Katete",
    "Kalomo",
    "Kalabo",
    "Chunga",
    "Madido",
  ],
  "Zimbabwe": [
    "Harare",
    "Bulawayo",
    "Chitungwiza",
    "Mutare",
    "Gweru",
    "Kwekwe",
    "Kadoma",
    "Masvingo",
    "Ruwa",
    "Karoi",
    "Gokwe",
    "Rusape",
    "Norton",
    "Mvurwi",
    "Kariba",
    "Hwange",
    "Gwanda",
    "Chegutu",
    "Bindura",
    "Epworth",
    "Shurugwi",
    "Redcliff",
    "Chiredzi",
    "Chipinge",
    "Chinhoyi",
    "Marondera",
    "Zvishavane",
    "Beitbridge",
    "Mount Hampden",
    "Victoria Falls",
  ],
  "Anguilla": [
    "The Valley",
  ],
  "American Samoa": [
    "Pago Pago",
  ],
  "Aruba": [
    "Noord",
    "Santa Cruz",
    "Oranjestad",
    "Tanki Leendert",
  ],
  "Åland Islands": [
    "Mariehamn",
  ],
  "Saint Barthélemy": [
    "Gustavia",
  ],
  "Bermuda": [
    "Hamilton",
  ],
  "Brunei Darussalam": [
    "Seria",
    "Liang",
    "Tutong",
    "Serasa",
    "Mentiri",
    "Sengkurong",
    "Kuala Belait",
    "Bandar Seri Begawan",
  ],
  "Bonaire": [
    "Kralendijk",
  ],
  "Cocos (Keeling) Islands": [
    "West Island",
  ],
  "Central African Republic": [
    "Ippy",
    "Bria",
    "Nola",
    "Kabo",
    "Abba",
    "Zemio",
    "Ndélé",
    "Sibut",
    "Paoua",
    "Dekoa",
    "Bouca",
    "Bouar",
    "Boali",
    "Bimbo",
    "Baoro",
    "Yaloké",
    "Mbaïki",
    "Carnot",
    "Bozoum",
    "Bégoua",
    "Bangui",
    "Baboua",
    "Bambari",
    "Alindao",
    "Kouango",
    "Bobangui",
    "Bangassou",
    "Bossangoa",
    "Bocaranga",
    "Berbérati",
  ],
  "Côte d'Ivoire": [
    "Zou",
    "Man",
    "Para",
    "Oumé",
    "Kong",
    "Hiré",
    "Goya",
    "Divo",
    "Buyo",
    "Andé",
    "Zaïbo",
    "Zagné",
    "Touba",
    "Tanda",
    "Tabou",
    "Kolia",
    "Kahin",
    "Issia",
    "Guéyo",
    "Daloa",
    "Dabou",
    "Bouna",
    "Biéby",
    "Arrah",
    "Abobo",
    "Aboka",
    "Bonon",
    "Touih",
    "Watté",
    "Gnago",
  ],
  "Cook Islands": [
    "Avarua",
  ],
  "Deyang": [
    "Mianzhu",
    "Mianzhu",
  ],
  "Curaçao": [
    "Bandariba",
    "Willemstad",
  ],
  "Christmas Island": [
    "Flying Fish Cove",
  ],
  "Western Sahara": [
    "Dakhla",
    "El Marsa",
    "Laayoune",
    "Boujdour",
  ],
  "Santa Caterina i La Ribera": [
    "Sant Pere",
  ],
  "Falkland Islands (Malvinas)": [
    "Stanley",
  ],
  "Micronesia": [
    "Palikir",
  ],
  "Faroe Islands": [
    "Tórshavn",
  ],
  "French Guiana": [
    "Kourou",
    "Matoury",
    "Cayenne",
    "Rémire-Montjoly",
    "Saint-Laurent-du-Maroni",
  ],
  "Guernsey": [
    "Saint Peter Port",
  ],
  "Gibraltar": [
    "Gibraltar",
  ],
  "Greenland": [
    "Nuuk",
  ],
  "Guadeloupe": [
    "Le Moule",
    "Le Gosier",
    "Les Abymes",
    "Sainte-Rose",
    "Sainte-Anne",
    "Petit-Bourg",
    "Basse-Terre",
    "Baie-Mahault",
    "Pointe-à-Pitre",
    "Capesterre-Belle-Eau",
  ],
  "South Georgia and the South Sandwich Islands": [
    "Grytviken",
  ],
  "Guam": [
    "Hagåtña",
    "Tamuning",
    "Yigo Village",
    "Dededo Village",
    "Mangilao Village",
    "Tamuning-Tumon-Harmon Village",
  ],
  "Hong Kong": [
    "So Uk",
    "Wo Che",
    "Wah Fu",
    "Tai Po",
    "Shek O",
    "Fo Tan",
    "Jordan",
    "Lee On",
    "Tin Wan",
    "Tai Wai",
    "Sha Tin",
    "San Tin",
    "San Tin",
    "Lam Tin",
    "Kowloon",
    "Kam Tin",
    "Fanling",
    "Tai Koo",
    "Mei Foo",
    "Kai Tak",
    "Olympic",
    "Whampoa",
    "Yau Tong",
    "Wan Chai",
    "Tuen Mun",
    "Ting Kau",
    "Shek Lei",
    "Sai Kung",
    "Mong Kok",
    "Aberdeen",
  ],
  "Israel": [
    "Lod",
    "Yāfā",
    "Arad",
    "Acre",
    "Safed",
    "Yirkā",
    "Yehud",
    "Yavné",
    "Jaffa",
    "Tamra",
    "Ramla",
    "Haifa",
    "Eilat",
    "Afula",
    "Rahat",
    "Ariel",
    "H̱ura",
    "El‘ad",
    "Sderot",
    "Ofaqim",
    "Nesher",
    "Maghār",
    "H̱olon",
    "Hadera",
    "Gedera",
    "Dimona",
    "Ashdod",
    "Shoham",
    "Sakhnīn",
    "Reẖovot",
  ],
  "Isle of Man": [
    "Douglas",
  ],
  "Jersey": [
    "Saint Helier",
  ],
  "Saitama": [
    "Misato",
  ],
  "Korea": [
    "Anju",
    "Anak",
    "Uiju",
    "Buan",
    "Osan",
    "Asan",
    "Naju",
    "Muan",
    "Gumi",
    "Wabu",
    "Sunan",
    "Kosan",
    "Haeju",
    "Ŭndŏk",
    "Ŏrang",
    "Ranam",
    "Rajin",
    "Kilju",
    "Unggi",
    "Eisen",
    "Yeoju",
    "Yesan",
    "Wŏnju",
    "Wanju",
    "Ulsan",
    "Daegu",
    "Suwon",
    "Seoul",
    "Buyeo",
    "Busan",
  ],
  "Cayman Islands": [
    "West Bay",
    "George Town",
  ],
  "Lao People's Democratic Republic": [
    "Pakse",
    "Pakxan",
    "Sekong",
    "Xam Nua",
    "Thakhèk",
    "Borikhan",
    "Ban Xénô",
    "Vientiane",
    "Muang Xay",
    "Ban Khoan",
    "Vang Vieng",
    "Muang Sing",
    "Savannakhet",
    "Ban Laongam",
    "Ban Kèngkok",
    "Luang Prabang",
    "Ban Houakhoua",
    "Muang Phônsavan",
  ],
  "Saint Martin (French part)": [
    "Marigot",
  ],
  "Marshall Islands": [
    "Majuro",
    "Dalap-Uliga-Dorrit",
  ],
  "Macao": [
    "Sé",
    "Taipa",
    "Macau",
    "Luhuan",
    "Zhuojiacun",
    "Lai Chi Van",
  ],
  "Northern Mariana Islands": [
    "Saipan",
  ],
  "Martinique": [
    "Ducos",
    "Le Robert",
    "La Trinité",
    "Le Lamentin",
    "Le François",
    "Saint-Joseph",
    "Sainte-Marie",
    "Fort-de-France",
  ],
  "Montserrat": [
    "Brades",
    "Plymouth",
  ],
  "New Caledonia": [
    "Nouméa",
    "Dumbéa",
    "Mont-Dore",
  ],
  "Norfolk Island": [
    "Kingston",
  ],
  "Niue": [
    "Alofi",
  ],
  "French Polynesia": [
    "Faaa",
    "Papeete",
    "Punaauia",
  ],
  "Saint Pierre and Miquelon": [
    "Saint-Pierre",
  ],
  "Pitcairn": [
    "Adamstown",
  ],
  "Puerto Rico": [
    "Cayey",
    "Ponce",
    "Yauco",
    "Caguas",
    "Cataño",
    "Manatí",
    "Arecibo",
    "Bayamón",
    "Fajardo",
    "Guayama",
    "Humacao",
    "Carolina",
    "Guaynabo",
    "Mayagüez",
    "San Juan",
    "Aguadilla",
    "Levittown",
    "Vega Baja",
    "Candelaria",
    "Barceloneta",
    "Trujillo Alto",
  ],
  "Palau": [
    "Ngerulmud",
  ],
  "Réunion": [
    "Le Port",
    "Saint-Leu",
    "Le Tampon",
    "Saint-Paul",
    "Saint-Louis",
    "Saint-Denis",
    "Saint-André",
    "Saint-Pierre",
    "Saint-Joseph",
    "Sainte-Marie",
    "Saint-Benoît",
    "La Possession",
    "Sainte-Suzanne",
    "Piton Saint-Leu",
  ],
  "Russian Federation": [
    "Uva",
    "Ufa",
    "Sim",
    "Osa",
    "Gay",
    "Buy",
    "Bor",
    "Ob’",
    "Tver",
    "Tula",
    "Perm",
    "Orsk",
    "Orël",
    "Luga",
    "Kusa",
    "Klin",
    "Inza",
    "Igra",
    "Fili",
    "Enem",
    "Azov",
    "Asha",
    "Arsk",
    "Anna",
    "Uray",
    "Tara",
    "Rezh",
    "Omsk",
    "Inta",
    "Zima",
  ],
  "Saint Helena": [
    "Jamestown",
  ],
  "Svalbard and Jan Mayen": [
    "Longyearbyen",
  ],
  "Sint Maarten (Dutch part)": [
    "Philipsburg",
  ],
  "Syrian Arab Republic": [
    "Nubl",
    "Nawá",
    "Homs",
    "Dūmā",
    "Ţafas",
    "Tādif",
    "Şūrān",
    "Jāsim",
    "Qārah",
    "Idlib",
    "Ḩamāh",
    "Dar‘ā",
    "Dā‘il",
    "I‘zāz",
    "Hajīn",
    "Yabrūd",
    "Ţarţūs",
    "Tadmur",
    "Salqīn",
    "Şāfītā",
    "Qaţanā",
    "Maşyāf",
    "Manbij",
    "Jayrūd",
    "Jablah",
    "‘Irbīn",
    "Inkhil",
    "Aleppo",
    "Batabo",
    "Babīlā",
  ],
  "Turks and Caicos Islands": [
    "Cockburn Town",
    "Providenciales",
  ],
  "French Southern Territories": [
    "Port-aux-Français",
  ],
  "Timor-Leste": [
    "Suai",
    "Dili",
    "Aileu",
    "Likisá",
    "Baukau",
    "Atsabe",
    "Maubara",
    "Maliana",
    "Lospalos",
    "Venilale",
  ],
  "Türkiye": [
    "Of",
    "Van",
    "Mut",
    "Muş",
    "Çay",
    "Çat",
    "Bor",
    "Çan",
    "Oba",
    "Uşak",
    "Urla",
    "Tire",
    "Soma",
    "Söke",
    "Lice",
    "Kulu",
    "Kulp",
    "Kula",
    "Ağrı",
    "İdil",
    "Genç",
    "Foça",
    "Emet",
    "Çine",
    "Zile",
    "Ünye",
    "Şile",
    "Rize",
    "Ordu",
    "Oltu",
  ],
  "Holy See (Vatican City State)": [
    "Vatican City",
  ],
  "Virgin Islands": [
    "Road Town",
    "Saint Croix",
    "Charlotte Amalie",
  ],
  "Viet Nam": [
    "Bo",
    "Huế",
    "Chũ",
    "Vinh",
    "Ô Môn",
    "La Gi",
    "Hanoi",
    "Dĩ An",
    "Cô Tô",
    "Cờ Đỏ",
    "Cổ Đô",
    "Ba Vì",
    "Bà Nà",
    "Nghèn",
    "Óc Eo",
    "Bồ Đề",
    "Tây Hồ",
    "Tân An",
    "Tam Kỳ",
    "Sơn La",
    "Sa Dec",
    "Ba Đồn",
    "Pleiku",
    "Từ Sơn",
    "Phú Mỹ",
    "Phủ Lý",
    "Phú Đô",
    "Nhà Bè",
    "Mỹ Tho",
    "Mỹ Lại",
  ],
  "Wallis and Futuna": [
    "Mata-Utu",
  ],
  "No country found for alpha-2 code: XK": [
    "Pejë",
    "Istok",
    "Deçan",
    "Zvečan",
    "Vitina",
    "Shtime",
    "Gjilan",
    "Ferizaj",
    "Prizren",
    "Llazicë",
    "Dragash",
    "Gjakovë",
    "Vushtrri",
    "Pristina",
    "Podujeva",
    "Orahovac",
    "Glogovac",
    "Suva Reka",
    "Leposaviq",
    "Mitrovicë",
    "Kosovo Polje",
  ],
  "Mayotte": [
    "Koungou",
    "Kaouéni",
    "Dzaoudzi",
    "Mtsapéré",
    "Mamoudzou",
    "Labattoir",
  ],
  };






  function $(sel) { return document.querySelector(sel); }

  function citiesFor(country) {
    if (CITIES_BY_COUNTRY[country]) return CITIES_BY_COUNTRY[country];
    // Fall back to the country's capital (same name as the country entry's
    // capital list is not stored, so just return the country itself as a
    // single resolvable option).
    return null;
  }

  async function fetchCitiesFromEndpoint(country) {
    try {
      const qs = new URLSearchParams({ country });
      const res = await fetch(`/api/cities?${qs.toString()}`);
      if (!res.ok) return null;
      const data = await res.json();
      const cities = (data?.cities || []).filter(Boolean);
      return cities.length ? cities : null;
    } catch (e) {
      return null;
    }
  }

  function t(key, fallback) {
    try {
      const dict = (window.I18n && window.I18n.DICT) || {};
      const lang = window.I18n && window.I18n.getLang ? window.I18n.getLang() : 'en';
      return (dict[lang] && dict[lang][key] != null) ? dict[lang][key] : (fallback || key);
    } catch (e) { return fallback || key; }
  }

  function populateCities(cities) {
    const citySelect = $('.location-city');
    if (!citySelect) return;
    citySelect.disabled = false;
    citySelect.innerHTML = `<option value="">${t('location.selectCity', 'Select a city')}</option>` +
      cities.map((c) => `<option value="${escapeAttr(c)}">${escapeHtml(c)}</option>`).join('');
  }

  function uniqueCityNames(results) {
    const seen = new Set();
    const out = [];
    (results || []).forEach((r) => {
      const name = r?.name || r?.city;
      if (name && !seen.has(name)) {
        seen.add(name);
        out.push(name);
      }
    });
    return out;
  }

  function removeCountry(select, country) {
    if (!select) return;
    const opt = Array.from(select.options).find((o) => o.value === country);
    if (opt) opt.remove();
    select.value = '';
  }

  function escapeHtml(str) {
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
  }

  function escapeAttr(str) {
    return escapeHtml(str).replace(/"/g, '&quot;');
  }

  function openModal() {
    const backdrop = $('.location-modal-backdrop');
    if (!backdrop) return;
    const countrySelect = $('.location-country');
    if (countrySelect && countrySelect.options.length <= 1) {
      countrySelect.innerHTML = `<option value="">${t('location.selectCountry', 'Select a country')}</option>` +
        COUNTRIES.map((c) => `<option value="${c}">${c}</option>`).join('');
    }
    const citySelect = $('.location-city');
    if (citySelect) {
      const savedCountry = countrySelect?.value;
      if (savedCountry) {
        const cities = citiesFor(savedCountry);
        if (cities && cities.length) {
          populateCities(cities);
        } else {
          citySelect.innerHTML = `<option value="">${t('location.selectCountryFirst', 'Select a country first')}</option>`;
          citySelect.disabled = true;
        }
      } else {
        citySelect.innerHTML = `<option value="">${t('location.selectCountryFirst', 'Select a country first')}</option>`;
        citySelect.disabled = true;
      }
    }
    if (window.I18n && window.I18n.apply) window.I18n.apply();
    backdrop.hidden = false;
  }

  function closeModal() {
    const backdrop = $('.location-modal-backdrop');
    if (backdrop) backdrop.hidden = true;
  }

  async function resolveCity(country, cityName) {
    const qs = new URLSearchParams({ country, city: cityName, count: 5 });
    const res = await fetch(`/api/location?${qs.toString()}`);
    if (!res.ok) throw new Error('Location search failed');
    const data = await res.json();
    const results = (data?.results || []).filter(
      (r) => (r.country || '').trim().toLowerCase() === country.trim().toLowerCase()
    );
    return results[0] || data?.results?.[0];
  }

  async function fetchCitiesForCountry(country, query) {
    const qs = new URLSearchParams({ country, city: query, count: 50 });
    const res = await fetch(`/api/location?${qs.toString()}`);
    if (!res.ok) return [];
    const data = await res.json();
    return data?.results || [];
  }

  function wire() {
    const backdrop = $('.location-modal-backdrop');
    if (!backdrop) return;

    const geoBtn = $('.header__geo-button');
    if (geoBtn) geoBtn.addEventListener('click', openModal);

    backdrop.querySelector('.location-cancel')?.addEventListener('click', closeModal);
    backdrop.addEventListener('click', (e) => { if (e.target === backdrop) closeModal(); });

    const countrySelect = $('.location-country');
    const citySelect = $('.location-city');

    countrySelect?.addEventListener('change', async () => {
      const country = countrySelect.value;
      if (!citySelect) return;
      if (!country) {
        citySelect.innerHTML = `<option value="">${t('location.selectCountryFirst', 'Select a country first')}</option>`;
        citySelect.disabled = true;
        return;
      }

      // Prefer the comprehensive curated city list served by the backend
      // (covers every major city, e.g. Morocco). Fall back to the local
      // curated list, then to the live geocoding API.
      const endpointCities = await fetchCitiesFromEndpoint(country);
      if (endpointCities && endpointCities.length) {
        populateCities(endpointCities);
        return;
      }

      const localCities = citiesFor(country);
      if (localCities && localCities.length) {
        populateCities(localCities);
        return;
      }

      // No curated list: ask the geocoding API. If it returns nothing, the
      // country has no resolvable cities, so drop it from the dropdown.
      fetchCitiesForCountry(country, '')
        .then((results) => {
          const names = uniqueCityNames(results);
          if (names.length) {
            populateCities(names);
          } else {
            removeCountry(countrySelect, country);
            citySelect.innerHTML = `<option value="">${t('location.noCities', 'No cities available')}</option>`;
            citySelect.disabled = true;
          }
        })
        .catch(() => {
          citySelect.innerHTML = `<option value="">${t('location.noCities', 'No cities available')}</option>`;
          citySelect.disabled = true;
        });
    });

    const confirmBtn = backdrop.querySelector('.location-confirm');
    if (confirmBtn) {
      confirmBtn.addEventListener('click', async () => {
        const country = countrySelect?.value;
        const cityName = citySelect?.value?.trim();
        if (!country || !cityName) return;
        try {
          const r = await resolveCity(country, cityName);
          if (!r) return;
          window.__lastLatLon = { lat: Number(r.lat), lon: Number(r.lon) };
          try { localStorage.setItem('open-meteo-latlon', JSON.stringify(window.__lastLatLon)); } catch (e) {}
          try { localStorage.setItem('open-meteo-city', cityName); } catch (e) {}
          try { localStorage.setItem('open-meteo-country', country); } catch (e) {}
          closeModal();
          window.dispatchEvent(new CustomEvent('location:changed', { detail: window.__lastLatLon }));
        } catch (e) { console.error(e); }
      });
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', wire);
  } else {
    wire();
  }
})();
